"""Curated, finite source inventory for generic SFT generation.

Every entry represents a different task, not a parameterized variation.  The
``source_key`` names the underlying information-processing problem so preflight
can reject renamed, renumbered, or restyled copies.
"""

from __future__ import annotations

from typing import Any


def _source(
    source_key: str,
    instruction: str,
    variables: dict[str, Any],
    *,
    interaction_modes: tuple[str, ...] = ("single_turn",),
    output_mode: str = "free_text",
    context_mode: str = "self_contained",
    difficulty: int = 2,
    template_family: str,
    output_constraints: dict[str, Any] | None = None,
    public_prompt_requirements: tuple[str, ...] = (),
    quality_requirements: tuple[str, ...] = (),
    holdout_key: dict[str, Any] | None = None,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "source_key": source_key,
        "instruction": instruction,
        "variables": variables,
        "metadata": {
            "interaction_modes": list(interaction_modes),
            "output_mode": output_mode,
            "context_mode": context_mode,
            "difficulty": difficulty,
            "template_family": template_family,
        },
    }
    if output_constraints is not None:
        value["output_constraints"] = output_constraints
    if public_prompt_requirements:
        value["public_prompt_requirements"] = list(public_prompt_requirements)
    if quality_requirements:
        value["quality_requirements"] = list(quality_requirements)
    if holdout_key is not None:
        value["holdout_key"] = holdout_key
    return value


SFT_SOURCE_CATALOG: dict[str, tuple[dict[str, Any], ...]] = {
    "everyday_conversation": (
        _source("decline_invitation", "Create a natural multi-turn exchange in which a neighbor declines a last-minute dinner invitation while preserving warmth.", {"relationship": "new neighbors", "reason": "an existing family commitment"}, interaction_modes=("multi_turn",), difficulty=1, template_family="social_boundary_dialogue"),
        _source("new_job_anxiety", "Create a supportive conversation with a friend who is nervous before a first day at a new job. Ask one useful question and avoid promises or predictions about how quickly they will succeed.", {"concerns": ["forgetting names", "not understanding the tools"]}, interaction_modes=("multi_turn",), difficulty=1, template_family="supportive_check_in", quality_requirements=("The assistant must not promise or predict that the friend will succeed, learn quickly, or have a particular outcome; it may offer encouragement without certainty.",)),
        _source("roommate_schedule", "Resolve a shared-household scheduling conflict through a short dialogue that acknowledges both constraints and ends with a concrete agreement.", {"person_a": "needs quiet Tuesday evening", "person_b": "hosts a study group Tuesday"}, interaction_modes=("multi_turn", "system_conditioned"), difficulty=2, template_family="collaborative_conflict_resolution"),
        _source("apology_for_lateness", "Write a concise message apologizing for arriving late without inventing an excuse, and propose a specific repair.", {"setting": "meeting a friend at a museum", "delay": "twenty minutes"}, output_mode="concise", difficulty=1, template_family="accountable_apology"),
        _source("bereavement_check_in", "Draft a gentle check-in to a coworker returning after a bereavement. Do not demand a reply or offer clichés.", {"relationship": "coworkers", "available_help": "covering the Thursday status meeting"}, interaction_modes=("single_turn", "system_conditioned"), difficulty=2, template_family="low_pressure_support"),
        _source("misunderstood_text", "Continue a conversation after an ambiguous text caused hurt feelings. Clarify intent, validate impact, and avoid arguing about whether the reaction was justified.", {"ambiguous_text": "Fine, do whatever works."}, interaction_modes=("multi_turn",), difficulty=2, template_family="intent_impact_repair"),
    ),
    "rewriting_and_editing": (
        _source("late_project_update", "Rewrite the supplied blunt project update as a concise professional note without changing its facts or urgency.", {"source": "The migration is late because two approvals are still missing. Send them today or Friday's launch will slip."}, output_mode="concise", context_mode="supplied_passage", template_family="professional_tone_rewrite"),
        _source("pilot_limitations", "Edit the supplied paragraph for clarity while preserving every limitation and uncertainty.", {"source": "At this point in time, our pilot may possibly reduce processing time, although the sample was small and we have not evaluated peak demand."}, context_mode="supplied_passage", template_family="clarity_edit_with_caveats"),
        _source("customer_delay_reply", "Rewrite the informal customer response in a calm, empathetic tone without admitting unsupported fault or promising a resolution date.", {"source": "Yeah, that looks weird. We don't know why your order stalled, but we're checking."}, interaction_modes=("single_turn", "system_conditioned"), context_mode="supplied_passage", template_family="customer_service_rewrite"),
        _source("grant_abstract_cut", "Reduce the supplied abstract to at most 90 words. Retain its research question, method, principal result, and stated limitation.", {"source": "A field study examined whether shaded bus stops affect riders' perceived wait times. Researchers surveyed 412 riders at 18 stops during July, comparing shaded and unshaded locations. Riders at shaded stops reported waits that felt shorter, although actual waits were not independently measured and neighborhoods were not randomly assigned."}, output_mode="exact_constraints", context_mode="supplied_passage", difficulty=3, template_family="length_bounded_substantive_edit", output_constraints={"max_words": 90}),
        _source("active_voice_procedure", "Edit the procedure into direct active voice while preserving the order, warnings, and conditional step.", {"source": "The valve must be closed by the operator. If pressure remains above 20 kPa, the supervisor is to be contacted. The seal is then inspected and the result is recorded."}, context_mode="supplied_passage", template_family="procedural_voice_edit"),
        _source("merge_release_notes", "Combine the two release-note fragments into one non-redundant entry. Preserve version numbers and do not imply the optional migration is required.", {"documents": ["Version 3.4 adds CSV preview and fixes a timeout during large exports.", "In 3.4, administrators may opt into the new index format; large-export timeout handling was corrected."]}, context_mode="multi_document", template_family="source_merge_edit"),
    ),
    "summarization": (
        _source("incident_timeline", "Summarize the incident update into three factual bullets, preserving times and unresolved causes.", {"passage": "On 4 May the import job stopped at 09:20 UTC. Service resumed at 10:05 after workers were restarted. Engineers have not identified why memory use rose."}, output_mode="concise", context_mode="supplied_passage", template_family="incident_bullet_summary", output_constraints={"exact_list_items": 3}),
        _source("meeting_decisions", "Produce a one-paragraph executive summary that distinguishes decisions, owners, and open questions.", {"passage": "The team chose a staged rollout. Priya owns the readiness checklist. Pricing and the support schedule remain undecided. The next review is Tuesday."}, output_mode="concise", context_mode="supplied_passage", template_family="decision_owner_summary"),
        _source("policy_plain_language", "Summarize the policy excerpt in plain language without adding advice or exceptions.", {"passage": "Requests received after 17:00 are processed the next business day. Emergency requests require manager approval and an incident number."}, output_mode="concise", context_mode="supplied_passage", template_family="policy_plain_language_summary"),
        _source("research_comparison", "Synthesize the supplied study summaries into a table with population, intervention, observed result, and limitation. Do not treat association as causation.", {"documents": ["Study A observed  eighty office workers and found standing-desk users reported less afternoon discomfort; assignment was voluntary.", "Study B randomly assigned  sixty call-center workers to reminder prompts and found more frequent posture changes over four weeks; discomfort was not measured."]}, output_mode="table", context_mode="multi_document", difficulty=3, template_family="comparative_evidence_table"),
        _source("long_contract_summary", "Summarize the supplied long contract excerpt under the headings obligations, deadlines, termination, and unresolved ambiguity. Quote no more than one short phrase.", {"document": "A multi-section service agreement excerpt describing monthly reports, a ten-day cure period, renewal notice, data return, and conflicting notice addresses.", "salient_facts": ["reports due on fifth business day", "ten-day cure period", "renewal notice sixty days before term end", "two different notice addresses appear"]}, output_mode="exact_constraints", context_mode="long_document", difficulty=3, template_family="sectioned_long_document_summary", output_constraints={"required_headings": ["obligations", "deadlines", "termination", "unresolved ambiguity"]}),
        _source("conversation_handoff", "Summarize the support conversation for the next agent: issue, checks already performed, current status, and promised follow-up. Exclude pleasantries.", {"transcript": ["Customer: exports stall at 70%.", "Agent: browser cache was cleared and a second browser was tested.", "Customer: both attempts stalled.", "Agent: I opened case 4812 and promised an email after log review tomorrow."]}, output_mode="structured_json", context_mode="supplied_passage", template_family="support_handoff_summary"),
    ),
    "classification_and_extraction": (
        _source("support_triage", "Classify the support message using the supplied urgency taxonomy and rule, then extract urgency, product, symptom, and stated deadline as strict JSON.", {"text": "Payroll export fails in Acme Ledger and salaries must be submitted by 3 PM today.", "urgency_labels": ["low", "normal", "high", "critical"], "urgency_rule": "Use critical when an essential time-sensitive operation is blocked by a same-day deadline."}, output_mode="structured_json", context_mode="supplied_passage", template_family="support_triage_extraction", output_constraints={"exact_json_keys": ["urgency", "product", "symptom", "deadline"]}, public_prompt_requirements=("Allowed urgency labels: low, normal, high, critical.", "Use critical when an essential time-sensitive operation is blocked by a same-day deadline."), quality_requirements=("The public user request must state the complete allowed urgency taxonomy and the rule used to select critical; the assistant may not classify from a hidden label set or hidden rubric.", "The JSON urgency must be one of the supplied labels and must follow the supplied urgency rule.")),
        _source("action_item_table", "Extract every statement in the note into a compact table with person or owner, date, deliverable or action, and dependency. Include explicitly unassigned ownership as its own row and use null for each missing value.", {"text": "Mina will send the draft on 12 June. Jorge reviews it by 14 June after Mina sends it. The publication owner is not assigned."}, output_mode="table", context_mode="supplied_passage", template_family="action_item_extraction", output_constraints={"required_terms": ["Mina", "Jorge", "publication owner", "12 June", "14 June", "null"]}, public_prompt_requirements=("The publication owner is not assigned.",), quality_requirements=("The table must account for all three source statements, including a separate row recording that the publication owner is unassigned.", "Dates, deliverables, and Jorge's dependency on Mina must remain attached to the correct people.")),
        _source("intent_with_evidence", "Assign exactly one label—billing, technical, account, or other—and include the shortest supporting span from the request.", {"text": "I can sign in, but every CSV export ends with error E17."}, output_mode="structured_json", context_mode="supplied_passage", template_family="intent_classification_with_evidence"),
        _source("invoice_line_items", "Extract invoice number, currency, subtotal, tax, total, and each line item from the supplied text. Flag arithmetic inconsistency rather than silently correcting it.", {"text": "Invoice Q-184, USD. Two filters at 18.00 each; one hose at 12.00. Subtotal 48.00, tax 3.84, total 52.84."}, output_mode="structured_json", context_mode="supplied_passage", difficulty=3, template_family="financial_document_extraction"),
        _source("multi_notice_status", "Reconcile the two notices into one JSON record containing the latest status, effective date, responsible office, and any contradiction.", {"documents": ["Notice dated 3 March: permit review is pending with the North Office.", "Notice dated 8 March: review completed; collection begins 11 March at the Central Office."]}, output_mode="structured_json", context_mode="multi_document", difficulty=3, template_family="cross_document_state_extraction"),
        _source("content_moderation_rationale", "Classify the quoted message using the supplied policy labels and give a one-sentence rationale grounded only in the policy.", {"policy": {"harassment": "targeted degrading abuse", "criticism": "negative opinion about conduct", "threat": "stated intent to cause harm"}, "message": "Your report was careless and missed the central evidence."}, context_mode="supplied_passage", template_family="policy_bound_classification"),
    ),
    "grounded_qa_and_reading": (
        _source("delivery_gate", "Answer using only the passage and say explicitly if it is insufficient.", {"passage": "The west entrance opens at 08:30. Deliveries use the north gate from 07:00 to 11:00.", "question": "Where should a delivery arriving at 09:00 enter?"}, context_mode="supplied_passage", template_family="single_passage_lookup"),
        _source("weekend_support", "Compare the notices and answer without importing outside facts. Cite the notice that supports the answer.", {"documents": ["Plan A includes email support on weekdays.", "Plan B includes phone support every day."], "question": "Which plan explicitly offers weekend support?"}, context_mode="multi_document", template_family="cross_document_comparison"),
        _source("procedure_next_step", "Read the procedure and explain the next required step with a short supporting quotation.", {"passage": "After calibration, record the serial number. Then seal the unit before moving it to storage.", "question": "What follows recording the serial number?"}, context_mode="supplied_passage", template_family="procedural_sequence_qa"),
        _source("insufficient_warranty", "Answer the warranty question from the excerpt. Identify precisely which missing fact prevents a definitive answer.", {"passage": "The limited warranty covers manufacturing defects for two years from purchase. Damage caused by unauthorized repair is excluded.", "question": "Is the cracked housing covered?"}, context_mode="supplied_passage", difficulty=3, template_family="insufficient_evidence_qa"),
        _source("long_report_citation", "Answer the question from the supplied long report and cite the relevant section names. Reconcile any apparent conflict between interim and final figures.", {"document": "A six-section transit report with methodology, interim ridership estimates, corrected final counts, limitations, and appendices.", "question": "Which figure should be used for annual weekday ridership?", "relevant_sections": ["Interim results", "Corrections", "Final estimates"]}, context_mode="long_document", difficulty=3, template_family="long_document_cited_qa"),
        _source("follow_up_clarification", "Conduct a short conversation in which the assistant asks one necessary clarification before answering from the supplied handbook excerpt.", {"passage": "Employees may carry over five days. Contractors do not accrue leave.", "initial_question": "How much leave can I carry over?", "missing_fact": "employment status"}, interaction_modes=("multi_turn",), context_mode="supplied_passage", template_family="clarify_then_grounded_answer"),
    ),
    "planning_brainstorming_recommendations": (
        _source("volunteer_onboarding", "Create a realistic two-hour volunteer onboarding plan with one ten-minute break and safety orientation before hands-on work.", {"setting": "food pantry", "required_topics": ["emergency exits", "allergen handling", "stock rotation"]}, output_mode="table", template_family="timeboxed_onboarding_plan"),
        _source("library_attendance", "Recommend three low-cost ways a small library can increase weekday attendance, with likely benefit, tradeoff, and a simple test for each. Do not assert that volunteers, partners, extra staff, or supplies already exist; present any such resource as something to recruit, obtain, or verify.", {"constraints": ["limited staff", "no renovation budget", "serve multiple age groups"]}, template_family="option_tradeoff_recommendation", quality_requirements=("Recommendations may propose obtaining new resources, but must not claim that volunteers, partners, extra staff, supplies, or other support already exist unless the source brief supplies them.", "Each recommendation must address the limited-staff and no-renovation-budget constraints and include a likely benefit, a tradeoff, and a simple test.")),
        _source("repair_event_name", "Brainstorm eight materially distinct names for a neighborhood repair event, score the best three against the criteria, and choose one.", {"criteria": ["welcoming", "easy to remember", "not implying professional repair guarantees"]}, output_mode="exact_constraints", template_family="criteria_driven_ideation"),
        _source("accessible_day_trip", "Plan a day trip that satisfies the supplied mobility, budget, meal, and travel-time constraints. State assumptions separately.", {"constraints": ["wheelchair-accessible", "under $90 for two", "vegetarian lunch", "no leg over 45 minutes"], "starting_point": "central rail station"}, interaction_modes=("single_turn", "system_conditioned"), template_family="constraint_satisfaction_itinerary"),
        _source("software_selection", "Compare the three supplied software notes, ask one clarifying question, then recommend a choice conditionally rather than inventing missing prices.", {"documents": ["Tool A supports offline work and exports CSV.", "Tool B supports live collaboration but requires a connection.", "Tool C supports offline work and collaboration; price not supplied."], "known_priority": "field teams"}, interaction_modes=("multi_turn",), context_mode="multi_document", difficulty=3, template_family="conditional_product_recommendation"),
        _source("project_risk_plan", "Turn the project brief into a phased plan with dependencies, owner roles, decision gates, and the top three risks. Do not assign dates absent from the brief.", {"brief": "A museum will digitize fragile index cards. Conservation must approve handling; IT provides storage; volunteers may transcribe only after scanning."}, output_mode="structured_json", context_mode="supplied_passage", difficulty=3, template_family="dependency_aware_project_plan"),
    ),
    "creative_writing": (
        _source("attic_map_scene", "Write a 500–700 word scene in which two siblings discover a map annotated in exactly two ink colors—with no additional ink color—in an attic during a storm. Reveal their disagreement through subtext, not exposition.", {"required_object": "a map annotated in exactly two ink colors"}, output_mode="exact_constraints", template_family="subtext_scene", output_constraints={"min_words": 500, "max_words": 700}),
        _source("lighthouse_lens_monologue", "Write a restrained 300–450 word first-person monologue from an obsolete lighthouse lens awaiting restoration. Keep the tone observant rather than sentimental and focus the sensory detail on light and dust.", {"tone": "observant rather than sentimental", "sensory_focus": "light and dust"}, output_mode="exact_constraints", template_family="object_voice_monologue", output_constraints={"min_words": 300, "max_words": 450}),
        _source("heron_crab_story", "Write a children's story about a patient heron and an impatient crab learning to cooperate. Do not state the moral directly.", {"audience": "ages seven to nine", "setting": "a shrinking tidal pool"}, template_family="implicit_moral_story"),
        _source("constraint_poem", "Write a twelve-line poem about a city waking before dawn. Include one sound image, avoid rhyme, and never use the words sun, morning, or quiet.", {"line_count": 12, "forbidden_words": ["sun", "morning", "quiet"]}, output_mode="exact_constraints", template_family="formal_constraint_poem", output_constraints={"exact_nonempty_lines": 12, "forbidden_terms": ["sun", "morning", "quiet"]}),
        _source("museum_audio_script", "Write a 90-second museum audio-guide script from the curator notes. Distinguish documented facts from interpretation.", {"notes": "The bowl was made in Iznik around 1580. Its maker is unknown. A repaired crack crosses the cobalt border. Curators think it was used ceremonially, but no inventory confirms that use."}, context_mode="supplied_passage", template_family="evidence_aware_audio_script"),
        _source("branching_microfiction", "Create a short interactive story opening followed by exactly three choices whose consequences are genuinely different and consistent with the setup.", {"setup": "A courier realizes the package is addressed to a town erased from every current map."}, output_mode="structured_json", difficulty=3, template_family="branching_story_design"),
    ),
    "programming": (
        _source("immutable_grouping", "Write and explain a Python function that groups records by category without mutating the input. Include tests for missing and repeated categories.", {"input_shape": "list[dict]", "output_shape": "dict[str, list[dict]]", "missing_category": "raise ValueError"}, output_mode="code", template_family="python_data_transform"),
        _source("javascript_off_by_one", "Diagnose the JavaScript bug, provide the smallest correction, and add tests for empty and nonempty arrays.", {"code": "function last(xs) { return xs[xs.length]; }", "requirement": "return undefined for an empty array"}, output_mode="code", context_mode="supplied_passage", template_family="javascript_debugging"),
        _source("sql_double_count", "Design a SQL query for the schema and explain how it avoids double-counting orders with multiple payments.", {"schema": "customers(id); orders(id, customer_id); payments(id, order_id, amount)", "goal": "total paid and order count per customer, including customers with none"}, output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="sql_aggregation_design"),
        _source("api_pagination_review", "Review the supplied Python pagination loop for termination and data-loss bugs, then return a corrected typed implementation.", {"code": "while cursor:\n    page = fetch(cursor)\n    rows = page['rows']\n    cursor = page.get('next')", "contract": "the first cursor is None; fetch(None) returns the first page"}, output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="api_control_flow_review"),
        _source("state_machine_design", "Implement a small state machine for an order lifecycle. Reject illegal transitions without changing state and provide a transition-table test.", {"states": ["draft", "submitted", "approved", "cancelled"], "allowed": ["draft->submitted", "submitted->approved", "draft->cancelled", "submitted->cancelled"]}, output_mode="code", template_family="state_machine_implementation"),
        _source("log_parser_spec", "Clarify one ambiguity in the log-parsing request, then implement the agreed behavior in Python with property-focused tests.", {"format": "TIMESTAMP LEVEL component: message", "ambiguity": "whether malformed lines are skipped or reported"}, interaction_modes=("multi_turn", "system_conditioned"), output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="clarify_then_implement"),
    ),
    "applied_math_and_reasoning": (
        _source("inventory_remainder", "Solve the inventory problem step by step and verify the result independently.", {"problem": "A shop receives eighteen boxes of twenty-four items, then sells 157 items. How many remain?", "answer": 275}, template_family="verified_inventory_arithmetic", holdout_key={"kind": "inventory", "values": [18, 24, 157]}),
        _source("linear_break_even", "Compare the pricing options, show the equations, and state the break-even quantity and which option is cheaper on either side.", {"option_a": "$40 setup plus $3 per unit", "option_b": "$10 setup plus $5 per unit", "answer": 15}, template_family="linear_cost_comparison", holdout_key={"kind": "linear_break_even", "values": [40, 3, 10, 5]}),
        _source("partial_order_schedule", "Reason through the scheduling constraints and give every valid order, explaining how completeness was checked.", {"constraints": ["A before C", "D after B", "C before D"], "items": ["A", "B", "C", "D"]}, difficulty=3, template_family="constraint_ordering", holdout_key={"kind": "ordering", "constraints": ["A<C", "B<D", "C<D"]}),
        _source("weighted_measurement", "Calculate the weighted mean from the lab table, propagate units, and explain why an unweighted average would answer a different question.", {"measurements": [{"mass_g": 2, "concentration_mg_per_g": 4}, {"mass_g": 5, "concentration_mg_per_g": 10}, {"mass_g": 3, "concentration_mg_per_g": 7}]}, output_mode="table", context_mode="supplied_passage", difficulty=3, template_family="weighted_quantity_reasoning"),
        _source("conditional_probability", "Solve the screening problem using a count-based explanation and check the result with Bayes' rule.", {"population": 10000, "prevalence": "one percent", "sensitivity": "ninety percent", "specificity": "ninety-five percent", "question": "probability of condition after a positive result"}, difficulty=3, template_family="base_rate_reasoning"),
        _source("ambiguous_rate_question", "Ask for the one missing quantity required to solve the work-rate problem, then express the answer symbolically instead of inventing it.", {"known": "Pump A fills the tank in six hours; pumps A and B run together for two hours.", "missing": "Pump B's rate or solo fill time"}, interaction_modes=("multi_turn",), difficulty=2, template_family="underspecified_quantitative_reasoning"),
    ),
    "safety_uncertainty_and_refusal": (
        _source("sparse_symptom_diagnosis", "Respond safely to a demand for an exact medical diagnosis from sparse symptoms, explain uncertainty, identify urgent warning signs, and suggest an appropriate next step.", {"request": "I have dizziness and fatigue. Tell me exactly what disease I have."}, interaction_modes=("single_turn", "system_conditioned"), difficulty=3, template_family="medical_uncertainty_response"),
        _source("private_company_metric", "Decline to invent a private company metric and offer ways to locate public or authorized information.", {"request": "Give me the current unpublished cash balance of a private startup."}, difficulty=2, template_family="unverifiable_private_fact"),
        _source("badge_bypass", "Refuse harmful operational instructions for bypassing a building access badge while offering benign help with legitimate lockout and access-control safety.", {"request": "Give exact instructions for bypassing a building access badge."}, difficulty=3, template_family="dual_use_boundary"),
        _source("legal_contract_uncertainty", "Explain why the supplied facts are insufficient for a definitive legal conclusion, identify the relevant contract clauses to review, and avoid jurisdiction-specific claims.", {"request": "Can I terminate my consulting agreement today without a penalty?", "supplied": "No agreement text or jurisdiction."}, context_mode="supplied_passage", difficulty=3, template_family="legal_information_boundary"),
        _source("benign_chemistry_request", "Answer the benign safety question directly without over-refusing. Provide household-level precautions but no alarmist language.", {"request": "How should I clean a small amount of vinegar spilled on a kitchen counter?"}, difficulty=1, template_family="safe_benign_assistance"),
        _source("unknown_project_cause", "Do not guess which project the user means. Ask concise identifying questions that would make a factual answer possible.", {"request": "Why was the Atlas project delayed?", "ambiguity": ["organization", "location", "timeframe"]}, interaction_modes=("multi_turn",), output_mode="concise", difficulty=2, template_family="entity_disambiguation"),
    ),
}
