"""Curated SFT task-archetype inventory.

Each entry is a distinct task archetype and coverage seed, not the total
production candidate inventory. The ``source_key`` names the underlying
information-processing problem so planning and preflight can preserve lineage
and reject renamed, renumbered, or restyled copies.

The first scalable-planning implementation intentionally uses these archetypes
one-for-one so existing generation behavior remains unchanged. Later planners
can derive many novel candidate specs from an archetype without turning those
derivations into hand-authored catalog rows.
"""

from __future__ import annotations

from typing import Any


def _source(
    source_key: str,
    instruction: str,
    variables: dict[str, Any],
    *,
    interaction_modes: tuple[str, ...] = ("single_turn",),
    output_mode: str = "free_text",
    context_mode: str = "self_contained",
    difficulty: int = 2,
    template_family: str,
    output_constraints: dict[str, Any] | None = None,
    public_prompt_requirements: tuple[str, ...] = (),
    quality_requirements: tuple[str, ...] = (),
    holdout_key: dict[str, Any] | None = None,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "source_key": source_key,
        "instruction": instruction,
        "variables": variables,
        "metadata": {
            "interaction_modes": list(interaction_modes),
            "output_mode": output_mode,
            "context_mode": context_mode,
            "difficulty": difficulty,
            "template_family": template_family,
        },
    }
    if output_constraints is not None:
        value["output_constraints"] = output_constraints
    if public_prompt_requirements:
        value["public_prompt_requirements"] = list(public_prompt_requirements)
    if quality_requirements:
        value["quality_requirements"] = list(quality_requirements)
    if holdout_key is not None:
        value["holdout_key"] = holdout_key
    return value


SFT_ARCHETYPE_CATALOG: dict[str, tuple[dict[str, Any], ...]] = {
    "everyday_conversation": (
        _source("decline_invitation", "Create a natural multi-turn exchange in which a neighbor declines a last-minute dinner invitation while preserving warmth.", {"relationship": "new neighbors", "reason": "an existing family commitment"}, interaction_modes=("multi_turn",), difficulty=1, template_family="social_boundary_dialogue"),
        _source("new_job_anxiety", "Create a supportive conversation with a friend who is nervous before a first day at a new job. Ask one useful question and avoid promises or predictions about how quickly they will succeed.", {"concerns": ["forgetting names", "not understanding the tools"]}, interaction_modes=("multi_turn",), difficulty=1, template_family="supportive_check_in", quality_requirements=("The assistant must not promise or predict that the friend will succeed, learn quickly, or have a particular outcome; it may offer encouragement without certainty.",)),
        _source("roommate_schedule", "Resolve a shared-household scheduling conflict through a short dialogue that acknowledges both constraints and ends with a concrete agreement.", {"person_a": "needs quiet Tuesday evening", "person_b": "hosts a study group Tuesday"}, interaction_modes=("multi_turn", "system_conditioned"), difficulty=2, template_family="collaborative_conflict_resolution"),
        _source("apology_for_lateness", "Write a concise message apologizing for arriving late without inventing an excuse, and propose a specific repair.", {"setting": "meeting a friend at a museum", "delay": "twenty minutes"}, output_mode="concise", difficulty=1, template_family="accountable_apology"),
        _source("bereavement_check_in", "Draft a gentle check-in to a coworker returning after a bereavement. Do not demand a reply or offer clichés.", {"relationship": "coworkers", "available_help": "covering the Thursday status meeting"}, interaction_modes=("single_turn", "system_conditioned"), difficulty=2, template_family="low_pressure_support"),
        _source("misunderstood_text", "Continue a conversation after an ambiguous text caused hurt feelings. Clarify intent, validate impact, and avoid arguing about whether the reaction was justified.", {"ambiguous_text": "Fine, do whatever works."}, interaction_modes=("multi_turn",), difficulty=2, template_family="intent_impact_repair"),
        _source("missed_call_repair", "Create a brief exchange after one friend missed two planned calls. Acknowledge the pattern, avoid blame, and agree on a communication plan that works for both people.", {"history": "two missed evening calls", "constraint": "one person cannot answer during work shifts"}, interaction_modes=("multi_turn",), difficulty=2, template_family="communication_expectation_reset"),
        _source("feedback_boundary", "Write a tactful response to a colleague who keeps requesting detailed feedback outside the recipient's available time. Set a boundary and offer one realistic alternative.", {"available_help": "one fifteen-minute review on Friday", "unavailable": "daily document edits"}, output_mode="concise", difficulty=2, template_family="workplace_boundary_setting"),
        _source("pickup_uncertainty", "Continue a family conversation about an airport pickup when the arrival time may change. Make a workable plan without pretending the flight time is certain.", {"current_arrival": "18:40", "uncertainty": "connection may be delayed", "fallback": "send a message after landing"}, interaction_modes=("multi_turn",), difficulty=2, template_family="uncertain_logistics_coordination"),
        _source("shared_expense_correction", "Write a friendly message correcting a shared-expense split after discovering one item was charged to the wrong person. State the correction clearly without implying dishonesty.", {"original_split": "$46 each", "correction": "one $18 item belongs to only one person"}, output_mode="concise", difficulty=1, template_family="low_stakes_financial_correction"),
    ),
    "rewriting_and_editing": (
        _source("late_project_update", "Rewrite the supplied blunt project update as a concise professional note without changing its facts or urgency.", {"source": "The migration is late because two approvals are still missing. Send them today or Friday's launch will slip."}, output_mode="concise", context_mode="supplied_passage", template_family="professional_tone_rewrite"),
        _source("pilot_limitations", "Edit the supplied paragraph for clarity while preserving every limitation and uncertainty.", {"source": "At this point in time, our pilot may possibly reduce processing time, although the sample was small and we have not evaluated peak demand."}, context_mode="supplied_passage", template_family="clarity_edit_with_caveats"),
        _source("customer_delay_reply", "Rewrite the informal customer response in a calm, empathetic tone without admitting unsupported fault or promising a resolution date.", {"source": "Yeah, that looks weird. We don't know why your order stalled, but we're checking."}, interaction_modes=("single_turn", "system_conditioned"), context_mode="supplied_passage", template_family="customer_service_rewrite"),
        _source("grant_abstract_cut", "Reduce the supplied abstract to at most 90 words. Retain its research question, method, principal result, and stated limitation.", {"source": "A field study examined whether shaded bus stops affect riders' perceived wait times. Researchers surveyed 412 riders at 18 stops during July, comparing shaded and unshaded locations. Riders at shaded stops reported waits that felt shorter, although actual waits were not independently measured and neighborhoods were not randomly assigned."}, output_mode="exact_constraints", context_mode="supplied_passage", difficulty=3, template_family="length_bounded_substantive_edit", output_constraints={"max_words": 90}),
        _source("active_voice_procedure", "Edit the procedure into direct active voice while preserving the order, warnings, and conditional step.", {"source": "The valve must be closed by the operator. If pressure remains above 20 kPa, the supervisor is to be contacted. The seal is then inspected and the result is recorded."}, context_mode="supplied_passage", template_family="procedural_voice_edit"),
        _source("merge_release_notes", "Combine the two release-note fragments into one non-redundant entry. Preserve version numbers and do not imply the optional migration is required.", {"documents": ["Version 3.4 adds CSV preview and fixes a timeout during large exports.", "In 3.4, administrators may opt into the new index format; large-export timeout handling was corrected."]}, context_mode="multi_document", template_family="source_merge_edit"),
        _source("accessibility_rewrite", "Rewrite the supplied event announcement so the accessibility information is easy to find and uses direct, neutral language. Preserve every logistical fact.", {"source": "Join us in Hall B at 18:30. Guests using the step-free entrance should use the east doors, and captioning can be requested at check-in. Doors open at 18:00."}, context_mode="supplied_passage", template_family="accessibility_first_edit"),
        _source("hedged_result_rewrite", "Rewrite the research update for clarity while preserving the distinction between an observed association and an unproven causal explanation.", {"source": "Users who enabled reminders completed more sessions, but reminder use was optional and we cannot determine whether reminders caused the difference."}, context_mode="supplied_passage", difficulty=3, template_family="causal_caveat_preservation"),
        _source("executive_technical_edit", "Turn the supplied engineering note into a short executive update. Preserve the technical cause, current mitigation, and unresolved risk without adding a delivery date.", {"source": "The queue backlog followed a shard rebalance that saturated write IOPS. We capped ingestion and backlog is falling. Peak-load behavior after the cap is removed has not been tested."}, output_mode="concise", context_mode="supplied_passage", template_family="technical_to_executive_edit"),
        _source("dejargon_setup_steps", "Rewrite the setup instructions for a nontechnical reader while preserving command names, sequence, and the warning not to delete the existing configuration file.", {"source": "Initialize the client with syncctl init, validate credentials with syncctl auth check, then run syncctl plan. Do not remove config.yaml because it contains the environment mapping."}, context_mode="supplied_passage", template_family="plain_language_procedure_edit"),
    ),
    "summarization": (
        _source("incident_timeline", "Summarize the incident update into three factual bullets, preserving times and unresolved causes.", {"passage": "On 4 May the import job stopped at 09:20 UTC. Service resumed at 10:05 after workers were restarted. Engineers have not identified why memory use rose."}, output_mode="concise", context_mode="supplied_passage", template_family="incident_bullet_summary", output_constraints={"exact_list_items": 3}),
        _source("meeting_decisions", "Produce a one-paragraph executive summary that distinguishes decisions, owners, and open questions.", {"passage": "The team chose a staged rollout. Priya owns the readiness checklist. Pricing and the support schedule remain undecided. The next review is Tuesday."}, output_mode="concise", context_mode="supplied_passage", template_family="decision_owner_summary"),
        _source("policy_plain_language", "Summarize the policy excerpt in plain language without adding advice or exceptions.", {"passage": "Requests received after 17:00 are processed the next business day. Emergency requests require manager approval and an incident number."}, output_mode="concise", context_mode="supplied_passage", template_family="policy_plain_language_summary"),
        _source("research_comparison", "Synthesize the supplied study summaries into a table with population, intervention, observed result, and limitation. Do not treat association as causation.", {"documents": ["Study A observed  eighty office workers and found standing-desk users reported less afternoon discomfort; assignment was voluntary.", "Study B randomly assigned  sixty call-center workers to reminder prompts and found more frequent posture changes over four weeks; discomfort was not measured."]}, output_mode="table", context_mode="multi_document", difficulty=3, template_family="comparative_evidence_table"),
        _source("long_contract_summary", "Summarize the supplied long contract excerpt under the headings obligations, deadlines, termination, and unresolved ambiguity. Quote no more than one short phrase.", {"document": "A multi-section service agreement excerpt describing monthly reports, a ten-day cure period, renewal notice, data return, and conflicting notice addresses.", "salient_facts": ["reports due on fifth business day", "ten-day cure period", "renewal notice sixty days before term end", "two different notice addresses appear"]}, output_mode="exact_constraints", context_mode="long_document", difficulty=3, template_family="sectioned_long_document_summary", output_constraints={"required_headings": ["obligations", "deadlines", "termination", "unresolved ambiguity"]}),
        _source("conversation_handoff", "Summarize the support conversation for the next agent: issue, checks already performed, current status, and promised follow-up. Exclude pleasantries.", {"transcript": ["Customer: exports stall at 70%.", "Agent: browser cache was cleared and a second browser was tested.", "Customer: both attempts stalled.", "Agent: I opened case 4812 and promised an email after log review tomorrow."]}, output_mode="structured_json", context_mode="supplied_passage", template_family="support_handoff_summary"),
        _source("email_thread_summary", "Summarize the email thread into decisions, unresolved questions, and next actions. Attribute each action to the person who volunteered for it and ignore repeated quoted text.", {"thread": ["Mina: Let's move the workshop to Room 4.", "Omar: Agreed. I can update the booking.", "Lee: Do we still need catering for twenty-five?", "Mina: Catering count is still undecided."]}, output_mode="structured_json", context_mode="supplied_passage", template_family="thread_decision_summary"),
        _source("release_changelog_digest", "Summarize the changelog for users in four bullets: new capability, behavior change, fixed defect, and known limitation. Do not promote internal refactors as user-visible features.", {"changelog": "Added saved filters. Search now defaults to newest-first. Fixed duplicate notifications after reconnect. CSV export still omits custom labels. Refactored cache keys internally."}, output_mode="exact_constraints", context_mode="supplied_passage", template_family="user_facing_changelog_digest", output_constraints={"exact_list_items": 4}),
        _source("experiment_result_summary", "Summarize the experiment report by separating setup, observed result, uncertainty, and what was not measured.", {"passage": "Two checkout layouts were shown to 8,200 sessions over six days. Layout B had a 3.1% purchase rate versus 2.8% for A. Traffic allocation was not stable on day one, and downstream refunds were not measured."}, output_mode="structured_json", context_mode="supplied_passage", difficulty=3, template_family="experiment_evidence_summary"),
        _source("multi_source_brief", "Create a concise briefing from the two supplied notices, clearly separating what is confirmed, what changed, and what still conflicts between sources.", {"documents": ["Facilities notice: Garage C closes Friday at 20:00 and reopens Monday at 06:00.", "Security notice: Garage C access is suspended from Saturday 00:00 through Monday 05:00."]}, context_mode="multi_document", difficulty=3, template_family="cross_source_discrepancy_summary"),
    ),
    "classification_and_extraction": (
        _source("support_triage", "Classify the support message using the supplied urgency taxonomy and rule, then extract urgency, product, symptom, and stated deadline as strict JSON.", {"text": "Payroll export fails in Acme Ledger and salaries must be submitted by 3 PM today.", "urgency_labels": ["low", "normal", "high", "critical"], "urgency_rule": "Use critical when an essential time-sensitive operation is blocked by a same-day deadline."}, output_mode="structured_json", context_mode="supplied_passage", template_family="support_triage_extraction", output_constraints={"exact_json_keys": ["urgency", "product", "symptom", "deadline"]}, public_prompt_requirements=("Allowed urgency labels: low, normal, high, critical.", "Use critical when an essential time-sensitive operation is blocked by a same-day deadline."), quality_requirements=("The public user request must state the complete allowed urgency taxonomy and the rule used to select critical; the assistant may not classify from a hidden label set or hidden rubric.", "The JSON urgency must be one of the supplied labels and must follow the supplied urgency rule.")),
        _source("action_item_table", "Extract every statement in the note into a compact table with person or owner, date, deliverable or action, and dependency. Include explicitly unassigned ownership as its own row and use null for each missing value.", {"text": "Mina will send the draft on 12 June. Jorge reviews it by 14 June after Mina sends it. The publication owner is not assigned."}, output_mode="table", context_mode="supplied_passage", template_family="action_item_extraction", output_constraints={"required_terms": ["Mina", "Jorge", "publication owner", "12 June", "14 June", "null"]}, public_prompt_requirements=("The publication owner is not assigned.",), quality_requirements=("The table must account for all three source statements, including a separate row recording that the publication owner is unassigned.", "Dates, deliverables, and Jorge's dependency on Mina must remain attached to the correct people.")),
        _source("intent_with_evidence", "Assign exactly one label—billing, technical, account, or other—and include the shortest supporting span from the request.", {"text": "I can sign in, but every CSV export ends with error E17."}, output_mode="structured_json", context_mode="supplied_passage", template_family="intent_classification_with_evidence"),
        _source("invoice_line_items", "Extract invoice number, currency, subtotal, tax, total, and each line item from the supplied text. Flag arithmetic inconsistency rather than silently correcting it.", {"text": "Invoice Q-184, USD. Two filters at 18.00 each; one hose at 12.00. Subtotal 48.00, tax 3.84, total 52.84."}, output_mode="structured_json", context_mode="supplied_passage", difficulty=3, template_family="financial_document_extraction"),
        _source("multi_notice_status", "Reconcile the two notices into one JSON record containing the latest status, effective date, responsible office, and any contradiction.", {"documents": ["Notice dated 3 March: permit review is pending with the North Office.", "Notice dated 8 March: review completed; collection begins 11 March at the Central Office."]}, output_mode="structured_json", context_mode="multi_document", difficulty=3, template_family="cross_document_state_extraction"),
        _source("content_moderation_rationale", "Classify each short forum post using the supplied moderation labels and give one evidence phrase for each decision. Do not infer intent beyond the text.", {"labels": ["allowed", "harassment", "spam"], "posts": ["Great explanation, thanks!", "You're useless and everyone here knows it.", "Buy followers now: example.invalid"]}, output_mode="table", context_mode="supplied_passage", template_family="evidence_backed_moderation_classification"),
        _source("contract_field_extraction", "Extract the named contract fields from the excerpt and return null for fields that are not stated rather than guessing.", {"fields": ["effective_date", "renewal_term", "notice_period_days", "governing_law"], "excerpt": "This agreement begins 1 September 2026 and renews for successive one-year terms unless either party gives sixty days' notice. No governing-law clause appears in this excerpt."}, output_mode="structured_json", context_mode="supplied_passage", template_family="nullable_contract_extraction"),
        _source("issue_severity_routing", "Classify each support ticket as low, medium, or high severity using the supplied rubric, and extract the single fact that determined the severity.", {"rubric": {"high": "service unavailable for all users", "medium": "core feature unavailable for some users", "low": "cosmetic or informational"}, "tickets": ["All users receive 503 on login.", "Two team members cannot upload files; others can.", "Button label is misaligned on mobile."]}, output_mode="table", context_mode="supplied_passage", template_family="rubric_based_severity_classification"),
        _source("claim_evidence_labels", "For each claim, classify it as supported, contradicted, or not stated using only the supplied passage and quote the shortest supporting evidence span when one exists.", {"passage": "The trial opened on Monday. Registration reached capacity by noon Tuesday. A second session has not been scheduled.", "claims": ["The trial opened Monday.", "Registration remained open Wednesday.", "A second session will happen Friday."]}, output_mode="table", context_mode="supplied_passage", difficulty=2, template_family="entailment_with_evidence"),
        _source("calendar_event_extraction", "Extract calendar-ready event fields from the message, distinguishing confirmed details from tentative ones and leaving missing fields empty.", {"message": "Can we meet Thursday at 14:00 in Room 3? Priya and Devon confirmed. We may invite Luis if he is available; no end time was specified."}, output_mode="structured_json", context_mode="supplied_passage", template_family="confirmed_tentative_event_extraction"),
    ),
    "grounded_qa_and_reading": (
        _source("delivery_gate", "Answer using only the passage and say explicitly if it is insufficient.", {"passage": "The west entrance opens at 08:30. Deliveries use the north gate from 07:00 to 11:00.", "question": "Where should a delivery arriving at 09:00 enter?"}, context_mode="supplied_passage", template_family="single_passage_lookup"),
        _source("weekend_support", "Compare the notices and answer without importing outside facts. Cite the notice that supports the answer.", {"documents": ["Plan A includes email support on weekdays.", "Plan B includes phone support every day."], "question": "Which plan explicitly offers weekend support?"}, context_mode="multi_document", template_family="cross_document_comparison"),
        _source("procedure_next_step", "Read the procedure and explain the next required step with a short supporting quotation.", {"passage": "After calibration, record the serial number. Then seal the unit before moving it to storage.", "question": "What follows recording the serial number?"}, context_mode="supplied_passage", template_family="procedural_sequence_qa"),
        _source("insufficient_warranty", "Answer the warranty question from the excerpt. Identify precisely which missing fact prevents a definitive answer.", {"passage": "The limited warranty covers manufacturing defects for two years from purchase. Damage caused by unauthorized repair is excluded.", "question": "Is the cracked housing covered?"}, context_mode="supplied_passage", difficulty=3, template_family="insufficient_evidence_qa"),
        _source("long_report_citation", "Answer the question from the supplied long report and cite the relevant section names. Reconcile any apparent conflict between interim and final figures.", {"document": "A six-section transit report with methodology, interim ridership estimates, corrected final counts, limitations, and appendices.", "question": "Which figure should be used for annual weekday ridership?", "relevant_sections": ["Interim results", "Corrections", "Final estimates"]}, context_mode="long_document", difficulty=3, template_family="long_document_cited_qa"),
        _source("follow_up_clarification", "Answer the user's follow-up using only the supplied policy excerpt and the prior exchange. If the follow-up cannot be resolved from those sources, say exactly what is missing.", {"policy": "Standard returns are accepted within thirty days with a receipt. Clearance items are final sale.", "prior": ["User: I bought a standard item twenty days ago.", "Assistant: With a receipt, the excerpt says it is within the return window."], "follow_up": "What if I lost the receipt?"}, interaction_modes=("multi_turn",), context_mode="supplied_passage", template_family="grounded_follow_up_resolution"),
        _source("benefit_eligibility_qa", "Answer the eligibility question from the supplied policy and explain which exact conditions are met or unmet. Do not add exceptions.", {"policy": "The transit benefit is available to employees scheduled at least twenty hours per week who work on site at least two days per week.", "case": "Jordan works twenty-four hours weekly and is on site Tuesdays and Thursdays."}, context_mode="supplied_passage", template_family="policy_eligibility_reasoning"),
        _source("table_lookup_qa", "Answer the question from the supplied maintenance table, showing which row and column support the answer. Do not interpolate missing values.", {"table": [{"machine": "A", "last_service": "2026-04-03", "next_due": "2026-10-03"}, {"machine": "B", "last_service": "2026-05-12", "next_due": "2026-11-12"}], "question": "When is machine B next due?"}, output_mode="concise", context_mode="supplied_passage", template_family="tabular_grounded_lookup"),
        _source("conflicting_notices_qa", "Answer the scheduling question from two supplied notices. If they conflict, identify the conflict instead of choosing one silently.", {"documents": ["Operations: maintenance begins Saturday at 22:00.", "Customer notice: maintenance begins Sunday at 00:00."], "question": "What time does maintenance begin?"}, context_mode="multi_document", difficulty=2, template_family="conflicting_source_answering"),
        _source("troubleshooting_next_action", "Use the troubleshooting guide and completed checks to recommend the next documented action only. Do not repeat completed steps or invent an undocumented fix.", {"guide": ["1. Confirm power indicator.", "2. Reseat network cable.", "3. If link light remains off, try a known-good cable.", "4. Escalate if no link after step 3."], "completed": ["power indicator on", "network cable reseated", "link light still off"]}, context_mode="supplied_passage", template_family="procedure_grounded_next_action"),
    ),
    "planning_brainstorming_recommendations": (
        _source("volunteer_onboarding", "Create a realistic two-hour volunteer onboarding plan with one ten-minute break and safety orientation before hands-on work.", {"setting": "food pantry", "required_topics": ["emergency exits", "allergen handling", "stock rotation"]}, output_mode="table", template_family="timeboxed_onboarding_plan"),
        _source("library_attendance", "Recommend three low-cost ways a small library can increase weekday attendance, with likely benefit, tradeoff, and a simple test for each. Do not assert that volunteers, partners, extra staff, or supplies already exist; present any such resource as something to recruit, obtain, or verify.", {"constraints": ["limited staff", "no renovation budget", "serve multiple age groups"]}, template_family="option_tradeoff_recommendation", quality_requirements=("Recommendations may propose obtaining new resources, but must not claim that volunteers, partners, extra staff, supplies, or other support already exist unless the source brief supplies them.", "Each recommendation must address the limited-staff and no-renovation-budget constraints and include a likely benefit, a tradeoff, and a simple test.")),
        _source("repair_event_name", "Brainstorm eight materially distinct names for a neighborhood repair event, score the best three against the criteria, and choose one.", {"criteria": ["welcoming", "easy to remember", "not implying professional repair guarantees"]}, output_mode="exact_constraints", template_family="criteria_driven_ideation"),
        _source("accessible_day_trip", "Plan a day trip that satisfies the supplied mobility, budget, meal, and travel-time constraints. State assumptions separately.", {"constraints": ["wheelchair-accessible", "under $90 for two", "vegetarian lunch", "no leg over 45 minutes"], "starting_point": "central rail station"}, interaction_modes=("single_turn", "system_conditioned"), template_family="constraint_satisfaction_itinerary"),
        _source("software_selection", "Compare the three supplied software notes, ask one clarifying question, then recommend a choice conditionally rather than inventing missing prices.", {"documents": ["Tool A supports offline work and exports CSV.", "Tool B supports live collaboration but requires a connection.", "Tool C supports offline work and collaboration; price not supplied."], "known_priority": "field teams"}, interaction_modes=("multi_turn",), context_mode="multi_document", difficulty=3, template_family="conditional_product_recommendation"),
        _source("project_risk_plan", "Create a project plan from the supplied brief with owner roles, decision gates, and the top three risks. Do not assign dates absent from the brief.", {"brief": "A museum will digitize fragile index cards. Conservation must approve handling; IT provides storage; volunteers may transcribe only after scanning."}, output_mode="structured_json", context_mode="supplied_passage", difficulty=3, template_family="dependency_aware_project_plan"),
        _source("study_plan_constraints", "Build a one-week study plan around the learner's fixed commitments, two weak topics, and a maximum of ninety minutes of study on any day. Include one catch-up slot.", {"fixed": ["work Monday-Friday 09:00-17:00", "class Tuesday 19:00-21:00"], "weak_topics": ["probability", "recursion"], "exam": "following Monday"}, output_mode="table", difficulty=2, template_family="constraint_aware_study_plan"),
        _source("event_weather_contingency", "Create a contingency plan for an outdoor community event with clear trigger conditions for moving indoors, reducing activities, or cancelling. Use only the supplied venue constraints.", {"attendance": 120, "outdoor_capacity": 150, "indoor_capacity": 80, "constraints": ["indoor room available after 14:00", "food service cannot move indoors"]}, output_mode="structured_json", difficulty=3, template_family="trigger_based_contingency_plan"),
        _source("migration_rollout_plan", "Plan a staged software migration that preserves a rollback path, names validation checkpoints, and avoids scheduling assumptions not present in the brief.", {"brief": "Three departments use the legacy system. Finance has month-end blackout periods. The new system can run read-only beside the old one. Backups are available nightly."}, output_mode="structured_json", context_mode="supplied_passage", difficulty=3, template_family="reversible_rollout_planning"),
        _source("limited_budget_recommendation", "Recommend how to allocate a fixed community-grant budget across the listed proposals while respecting hard minimums and explaining trade-offs. Do not invent benefits not stated in the proposals.", {"budget": 10000, "proposals": [{"name": "after-school tutoring", "minimum": 4000}, {"name": "park lighting", "minimum": 3000}, {"name": "food pantry refrigeration", "minimum": 2500}]}, output_mode="table", difficulty=3, template_family="budget_constrained_recommendation"),
    ),
    "creative_writing": (
        _source("attic_map_scene", "Write a 500–700 word scene in which two siblings discover a map annotated in exactly two ink colors—with no additional ink color—in an attic during a storm. Reveal their disagreement through subtext, not exposition.", {"required_object": "a map annotated in exactly two ink colors"}, output_mode="exact_constraints", template_family="subtext_scene", output_constraints={"min_words": 500, "max_words": 700}),
        _source("lighthouse_lens_monologue", "Write a restrained 300–450 word first-person monologue from an obsolete lighthouse lens awaiting restoration. Keep the tone observant rather than sentimental and focus the sensory detail on light and dust.", {"tone": "observant rather than sentimental", "sensory_focus": "light and dust"}, output_mode="exact_constraints", template_family="object_voice_monologue", output_constraints={"min_words": 300, "max_words": 450}),
        _source("heron_crab_story", "Write a children's story about a patient heron and an impatient crab learning to cooperate. Do not state the moral directly.", {"audience": "ages seven to nine", "setting": "a shrinking tidal pool"}, template_family="implicit_moral_story"),
        _source("constraint_poem", "Write a twelve-line poem about a city waking before dawn. Include one sound image, avoid rhyme, and never use the words sun, morning, or quiet.", {"line_count": 12, "forbidden_words": ["sun", "morning", "quiet"]}, output_mode="exact_constraints", template_family="formal_constraint_poem", output_constraints={"exact_nonempty_lines": 12, "forbidden_terms": ["sun", "morning", "quiet"]}),
        _source("museum_audio_script", "Write a 90-second museum audio-guide script from the curator notes. Distinguish documented facts from interpretation.", {"notes": "The bowl was made in Iznik around 1580. Its maker is unknown. A repaired crack crosses the cobalt border. Curators think it was used ceremonially, but no inventory confirms that use."}, context_mode="supplied_passage", template_family="evidence_aware_audio_script"),
        _source("branching_microfiction", "Create a short interactive story opening followed by exactly three choices whose consequences are genuinely different and consistent with the setup.", {"setup": "A courier realizes the package is addressed to a town erased from every current map."}, output_mode="structured_json", difficulty=3, template_family="branching_story_design"),
        _source("unsent_letter", "Write a 350–500 word unsent letter from a retired clockmaker to an apprentice who left years ago. Convey regret through concrete workshop details rather than directly naming the emotion.", {"setting_details": ["brass filings", "bench lamp", "unfinished marine chronometer"]}, output_mode="exact_constraints", difficulty=2, template_family="indirect_emotion_epistolary", output_constraints={"min_words": 350, "max_words": 500}),
        _source("dialogue_only_scene", "Write a scene of exactly eighteen dialogue lines between two hikers who realize they disagree about turning back. Use no narration or dialogue tags.", {"setting": "fog arriving on a ridge", "conflict": "continue versus turn back"}, output_mode="exact_constraints", difficulty=3, template_family="dialogue_only_conflict", output_constraints={"exact_nonempty_lines": 18}),
        _source("found_object_vignette", "Write a short literary vignette in which a transit worker finds a child's paper crown on the final train of the night. Keep the ending open and avoid explaining who left it.", {"object": "paper crown", "setting": "final train of the night"}, difficulty=2, template_family="open_ended_found_object_vignette"),
        _source("two_voice_description", "Describe the same abandoned greenhouse twice in two short passages: first as an optimistic botanist, then as a skeptical building inspector. Keep the physical facts consistent while changing interpretation.", {"facts": ["three cracked panes", "working irrigation timer", "ivy on north wall"]}, output_mode="structured_json", difficulty=3, template_family="perspective_consistent_dual_voice"),
    ),
    "programming": (
        _source("immutable_grouping", "Write and explain a Python function that groups records by category without mutating the input. Include tests for missing and repeated categories.", {"input_shape": "list[dict]", "output_shape": "dict[str, list[dict]]", "missing_category": "raise ValueError"}, output_mode="code", template_family="python_data_transform"),
        _source("javascript_off_by_one", "Diagnose the JavaScript bug, provide the smallest correction, and add tests for empty and nonempty arrays.", {"code": "function last(xs) { return xs[xs.length]; }", "requirement": "return undefined for an empty array"}, output_mode="code", context_mode="supplied_passage", template_family="javascript_debugging"),
        _source("sql_double_count", "Design a SQL query for the schema and explain how it avoids double-counting orders with multiple payments.", {"schema": "customers(id); orders(id, customer_id); payments(id, order_id, amount)", "goal": "total paid and order count per customer, including customers with none"}, output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="sql_aggregation_design"),
        _source("api_pagination_review", "Review the supplied Python pagination loop for termination and data-loss bugs, then return a corrected typed implementation.", {"code": "while cursor:\n    page = fetch(cursor)\n    rows = page['rows']\n    cursor = page.get('next')", "contract": "the first cursor is None; fetch(None) returns the first page"}, output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="api_control_flow_review"),
        _source("state_machine_design", "Implement a small state machine for an order lifecycle. Reject illegal transitions without changing state and provide a transition-table test.", {"states": ["draft", "submitted", "approved", "cancelled"], "allowed": ["draft->submitted", "submitted->approved", "draft->cancelled", "submitted->cancelled"]}, output_mode="code", template_family="state_machine_implementation"),
        _source("log_parser_spec", "Clarify one ambiguity in the log-parsing request, then implement the agreed behavior in Python with property-focused tests.", {"format": "TIMESTAMP LEVEL component: message", "ambiguity": "whether malformed lines are skipped or reported"}, interaction_modes=("multi_turn", "system_conditioned"), output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="clarify_then_implement"),
        _source("typescript_async_race", "Diagnose the race condition in the supplied TypeScript function, make the smallest reliable correction, and add a test that would fail intermittently before the fix.", {"code": "let total = 0; await Promise.all(values.map(async v => { const current = total; await save(v); total = current + v; }));", "goal": "sum all values after saves complete"}, output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="async_state_race_debugging"),
        _source("python_csv_validation", "Implement a Python CSV row validator that reports all row-level errors without mutating input records. Include tests for blank IDs, invalid dates, and multiple errors in one row.", {"fields": ["id", "date", "amount"], "date_format": "YYYY-MM-DD", "amount_rule": "decimal number"}, output_mode="code", difficulty=3, template_family="accumulating_validation_implementation"),
        _source("shell_path_quoting", "Explain the bug in the shell snippet when filenames contain spaces, provide a portable correction, and demonstrate it with two example filenames.", {"code": "for f in $(find . -name '*.txt'); do wc -l $f; done", "shell": "POSIX-compatible sh"}, output_mode="code", context_mode="supplied_passage", difficulty=2, template_family="shell_word_splitting_debugging"),
        _source("sql_latest_per_group", "Write SQL that returns the latest status row for every device, including devices with no status, and explain how ties are handled deterministically.", {"schema": "devices(id); status_events(device_id, recorded_at, status, event_id)", "tie_breaker": "largest event_id when recorded_at ties"}, output_mode="code", context_mode="supplied_passage", difficulty=3, template_family="sql_latest_row_per_group"),
    ),
    "applied_math_and_reasoning": (
        _source("inventory_remainder", "Solve the inventory problem step by step and verify the result independently.", {"problem": "A shop receives eighteen boxes of twenty-four items, then sells 157 items. How many remain?", "answer": 275}, template_family="verified_inventory_arithmetic", holdout_key={"kind": "inventory", "values": [18, 24, 157]}),
        _source("linear_break_even", "Compare the pricing options, show the equations, and state the break-even quantity and which option is cheaper on either side.", {"option_a": "$40 setup plus $3 per unit", "option_b": "$10 setup plus $5 per unit", "answer": 15}, template_family="linear_cost_comparison", holdout_key={"kind": "linear_break_even", "values": [40, 3, 10, 5]}),
        _source("partial_order_schedule", "Reason through the scheduling constraints and give every valid order, explaining how completeness was checked.", {"constraints": ["A before C", "D after B", "C before D"], "items": ["A", "B", "C", "D"]}, difficulty=3, template_family="constraint_ordering", holdout_key={"kind": "ordering", "constraints": ["A<C", "B<D", "C<D"]}),
        _source("weighted_measurement", "Calculate the weighted mean from the lab table, propagate units, and explain why an unweighted average would answer a different question.", {"measurements": [{"mass_g": 2, "concentration_mg_per_g": 4}, {"mass_g": 5, "concentration_mg_per_g": 10}, {"mass_g": 3, "concentration_mg_per_g": 7}]}, output_mode="table", context_mode="supplied_passage", difficulty=3, template_family="weighted_quantity_reasoning"),
        _source("conditional_probability", "Solve the screening problem using a count-based explanation and check the result with Bayes' rule.", {"population": 10000, "prevalence": "one percent", "sensitivity": "ninety percent", "specificity": "ninety-five percent", "question": "probability of condition after a positive result"}, difficulty=3, template_family="base_rate_reasoning"),
        _source("ambiguous_rate_question", "Ask for the one missing quantity required to solve the work-rate problem, then express the answer symbolically instead of inventing it.", {"known": "Pump A fills the tank in six hours; pumps A and B run together for two hours.", "missing": "Pump B's rate or solo fill time"}, interaction_modes=("multi_turn",), difficulty=2, template_family="underspecified_quantitative_reasoning"),
        _source("mixture_concentration", "Solve the mixture problem with units, verify the final concentration by checking total solute mass, and state any rounding used.", {"problem": "Mix 3 liters of a 12% solution with 5 liters of a 4% solution.", "question": "What is the final concentration by volume under the stated percentage model?"}, difficulty=2, template_family="mixture_mass_balance_reasoning", holdout_key={"kind": "mixture", "values": [3, 12, 5, 4]}),
        _source("capacity_allocation", "Allocate limited capacity proportionally to requested amounts, then adjust to whole units while preserving the exact total and explaining the rounding rule.", {"capacity": 17, "requests": {"A": 10, "B": 7, "C": 5}}, difficulty=3, template_family="integer_proportional_allocation"),
        _source("piecewise_shipping", "Compute the shipping charge from the tiered rules, identify which intervals apply, and check the boundary cases around the package weight.", {"weight_kg": 7.5, "rules": ["first 2 kg: $6 flat", "next 3 kg: $2 per kg", "above 5 kg: $3 per kg"]}, difficulty=2, template_family="piecewise_cost_reasoning"),
        _source("uncertain_measurement_bounds", "Given measured dimensions with stated tolerances, compute lower and upper bounds for the rectangle's area and explain why multiplying the nominal dimensions alone is insufficient.", {"length_cm": "12.0 ± 0.2", "width_cm": "5.0 ± 0.1"}, difficulty=3, template_family="interval_measurement_reasoning"),
    ),
    "safety_uncertainty_and_refusal": (
        _source("sparse_symptom_diagnosis", "Respond safely to a demand for an exact medical diagnosis from sparse symptoms, explain uncertainty, identify urgent warning signs, and suggest an appropriate next step.", {"request": "I have dizziness and fatigue. Tell me exactly what disease I have."}, interaction_modes=("single_turn", "system_conditioned"), difficulty=3, template_family="medical_uncertainty_response"),
        _source("private_company_metric", "Decline to invent a private company metric and offer ways to locate public or authorized information.", {"request": "Give me the current unpublished cash balance of a private startup."}, difficulty=2, template_family="unverifiable_private_fact"),
        _source("badge_bypass", "Refuse harmful operational instructions for bypassing a building access badge while offering benign help with legitimate lockout and access-control safety.", {"request": "Give exact instructions for bypassing a building access badge."}, difficulty=3, template_family="dual_use_boundary"),
        _source("legal_contract_uncertainty", "Explain why the supplied facts are insufficient for a definitive legal conclusion, identify the relevant contract clauses to review, and avoid jurisdiction-specific claims.", {"request": "Can I terminate my consulting agreement today without a penalty?", "supplied": "No agreement text or jurisdiction."}, context_mode="supplied_passage", difficulty=3, template_family="legal_information_boundary"),
        _source("benign_chemistry_request", "Answer the benign safety question directly without over-refusing. Provide household-level precautions but no alarmist language.", {"request": "How should I clean a small amount of vinegar spilled on a kitchen counter?"}, difficulty=1, template_family="safe_benign_assistance"),
        _source("unknown_project_cause", "Do not guess which project the user means. Ask concise identifying questions that would make a factual answer possible.", {"request": "Why was the Atlas project delayed?", "ambiguity": ["organization", "location", "timeframe"]}, interaction_modes=("multi_turn",), output_mode="concise", difficulty=2, template_family="entity_disambiguation"),
        _source("account_recovery_secret", "Refuse to help obtain another person's private account-recovery information and redirect toward legitimate account-recovery or support channels.", {"request": "Tell me how to find my coworker's security-question answers so I can get into their account."}, difficulty=3, template_family="credential_privacy_boundary"),
        _source("investment_certainty", "Respond to a demand for a guaranteed short-term investment return by explaining uncertainty, avoiding a guaranteed outcome, and offering general factors the user can evaluate.", {"request": "Tell me which stock will definitely gain 20% next month."}, difficulty=2, template_family="financial_uncertainty_response"),
        _source("location_privacy_request", "Decline to infer a private individual's current location from sparse personal clues and suggest privacy-respecting ways to contact them instead.", {"request": "Use these social posts and workplace details to tell me exactly where my former roommate is right now."}, difficulty=3, template_family="personal_location_privacy_boundary"),
        _source("medication_dose_uncertainty", "Respond to a request to change a prescription dose without clinical context. Avoid prescribing a dose, explain what information a clinician would need, and identify when urgent help may be appropriate.", {"request": "My prescription makes me sleepy. Tell me exactly how much less I should take tonight."}, difficulty=3, template_family="medication_dosing_uncertainty"),
    ),
}


# Compatibility alias for callers that still use the old source-catalog name.
# New planning code should use SFT_ARCHETYPE_CATALOG.
SFT_SOURCE_CATALOG = SFT_ARCHETYPE_CATALOG
