"""Shared Hugging Face dataset-card generation for public outputs."""

from __future__ import annotations

import argparse
from pathlib import Path


CARD_KINDS = {
    "pretrain": {
        "title": "SLM Synthetic Pretraining",
        "description": "Synthetic pretraining records generated by `slm-synthetic-data`.",
        "schema": """Each row contains public pretraining data.

Expected public fields:
- `id`: stable record identifier, when present
- `text`: training text
- `metadata`: source/category metadata, when present""",
    },
    "sft": {
        "title": "SLM Synthetic SFT",
        "description": "Synthetic supervised fine-tuning records generated by `slm-synthetic-data`.",
        "schema": """Each row contains one supervised chat-style training record.

Expected public fields:
- `id`: stable record identifier
- `messages`: ordered chat messages
  - user message
  - assistant message
- `metadata`: family/category/template/eval metadata""",
    },
    "dpo": {
        "title": "SLM Synthetic DPO",
        "description": "Synthetic preference pairs generated by `slm-synthetic-data`.",
        "schema": """Each row contains one preference pair.

Expected public fields:
- `id`: stable pair identifier
- `prompt` or `messages`: prompt context
- `chosen`: preferred assistant response
- `rejected`: rejected assistant response
- `metadata`: family/category/template/eval metadata""",
    },
    "distillation-sft": {
        "title": "SLM Synthetic Distillation SFT",
        "description": "Synthetic teacher-response distillation records generated by `slm-synthetic-data`.",
        "schema": """Each row contains one teacher response for response distillation.

Expected public fields:
- `id`: stable record identifier
- `prompt`: student-facing prompt
- `reasoning`: optional reasoning field
- `response`: teacher response""",
    },
    "distillation-dpo": {
        "title": "SLM Synthetic Distillation DPO",
        "description": "Synthetic teacher preference pairs generated by `slm-synthetic-data`.",
        "schema": """Each row contains one teacher preference pair for distillation alignment.

Expected public fields:
- `id`: stable pair identifier
- `prompt`: student-facing prompt
- `chosen`: preferred teacher response
- `rejected`: rejected teacher response""",
    },
}


HF_DATA_FILES_YAML = """---
configs:
- config_name: default
  data_files:
  - split: train
    path: data/*.jsonl
---
"""


def build_dataset_card(kind: str, *, run_id: str | None = None, title: str | None = None) -> str:
    """Return a standard HF dataset card for one public generation surface."""

    if kind not in CARD_KINDS:
        allowed = ", ".join(sorted(CARD_KINDS))
        raise ValueError(f"unknown dataset-card kind {kind!r}; expected one of: {allowed}")

    spec = CARD_KINDS[kind]
    card_title = title or spec["title"]
    lines = [
        HF_DATA_FILES_YAML.rstrip(),
        "",
        f"# {card_title}",
        "",
        spec["description"],
        "",
    ]

    if run_id:
        lines.extend(["## Run", "", f"`{run_id}`", ""])

    lines.extend(
        [
            "## Public data files",
            "",
            "Dataset rows are published under `data/*.jsonl`.",
            "",
            "Run metadata, coverage reports, and manifests are published under `artifacts/` and are not part of the dataset split.",
            "",
            "## Schema",
            "",
            spec["schema"],
            "",
        ]
    )

    return "\n".join(lines)


def write_dataset_card(
    kind: str,
    run_dir: str | Path,
    *,
    run_id: str | None = None,
    title: str | None = None,
) -> Path:
    """Write README.md into a generation run directory."""

    run_path = Path(run_dir)
    if run_id is None:
        run_id = run_path.name

    run_path.mkdir(parents=True, exist_ok=True)
    readme_path = run_path / "README.md"
    readme_path.write_text(
        build_dataset_card(kind, run_id=run_id, title=title),
        encoding="utf-8",
    )
    return readme_path


def _build_cli(args: argparse.Namespace) -> int:
    path = write_dataset_card(
        args.kind,
        args.run_dir,
        run_id=args.run_id,
        title=args.title,
    )
    print(f"[cards] wrote {path}")
    return 0


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build standard generation dataset cards.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="write README.md for a generation run")
    build_parser.add_argument("--kind", choices=sorted(CARD_KINDS), required=True)
    build_parser.add_argument("--run-dir", required=True)
    build_parser.add_argument("--run-id", default=None)
    build_parser.add_argument("--title", default=None)
    build_parser.set_defaults(func=_build_cli)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(cli())
