"""Shared Hugging Face dataset-card generation for public dataset outputs."""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from slm_synth.manifest_totals import load_run_manifest, public_dataset_stats


HF_DATA_FILES_YAML = """---
configs:
- config_name: default
  data_files:
  - split: train
    path: data/*.jsonl
---
"""


def build_hf_data_files_yaml(*, kind: str, signals: Iterable[str] | None = None) -> str:
    """Build dataset-card YAML with a default config and optional SFT family configs."""
    clean_signals = _clean_list(signals)
    lines = ["---", "configs:", "- config_name: default", "  data_files:", "  - split: train", "    path: data/*.jsonl"]
    if kind in {"sft", "dpo"}:
        for family in clean_signals:
            lines.extend(
                [
                    f"- config_name: {family}",
                    "  data_files:",
                    "  - split: train",
                    f"    path: data/{family}.jsonl",
                ]
            )
    lines.extend(["---", ""])
    return "\n".join(lines)


CARD_SPECS: dict[str, dict[str, str]] = {
    "pretrain": {
        "title": "SLM Synthetic Pretrain",
        "summary": "Synthetic pretraining records generated by `slm-synthetic-data`.",
        "dataset_type": "pretraining text",
        "unit_label": "Total records",
        "schema": """{
  "id": "string",
  "text": "string",
  "metadata": {
    "signal": "string"
  }
}""",
        "intended_use": "Use this dataset for small-language-model pretraining or data-mixing experiments.",
        "limitations": "This dataset is synthetic and should be inspected before training. It is not a benchmark.",
    },
    "sft": {
        "title": "SLM Synthetic SFT",
        "summary": "Synthetic supervised fine-tuning dataset containing prompt-response conversations.",
        "dataset_type": "supervised fine-tuning",
        "unit_label": "Total rows",
        "schema": """{
  "id": "string",
  "messages": [
    {"role": "user", "content": "string"},
    {"role": "assistant", "content": "string"}
  ],
  "metadata": {
    "task_family": "string",
    "interaction_modes": ["string"],
    "output_mode": "string",
    "context_mode": "string",
    "difficulty": 1,
    "template_family": "string"
  }
}""",
        "schema_note": (
            "`messages` is variable-length. Most rows are ordinary user/assistant "
            "exchanges. System messages, `tools`, assistant `tool_calls`, tool-result "
            "messages, and additional turns appear only when the row's interaction "
            "mode requires them."
        ),
        "intended_use": "Use this dataset for supervised fine-tuning experiments.",
        "limitations": "This dataset is synthetic. Inspect samples before training and do not use it as an evaluation benchmark.",
    },
    "dpo": {
        "title": "SLM Synthetic DPO",
        "summary": "Synthetic preference-pair dataset containing chosen and rejected assistant responses.",
        "dataset_type": "preference optimization",
        "unit_label": "Total pairs",
        "schema": """{
  "id": "string",
  "prompt": [
    {"role": "user", "content": "string"}
  ],
  "chosen": [
    {"role": "assistant", "content": "string"}
  ],
  "rejected": [
    {"role": "assistant", "content": "string"}
  ],
  "metadata": {
    "task_family": "string",
    "interaction_modes": ["string"],
    "output_mode": "string",
    "context_mode": "string",
    "difficulty": 1,
    "template_family": "string",
    "preference_dimension": "string",
    "failure_mode": "string"
  }
}""",
        "schema_note": (
            "`prompt`, `chosen`, and `rejected` are message lists. Tool definitions, "
            "assistant tool calls, tool-result messages, and multi-turn structures are "
            "included only for interaction modes that require them."
        ),
        "intended_use": "Use this dataset for DPO-style preference optimization experiments.",
        "limitations": "This dataset is synthetic and encodes targeted preference behavior. Inspect chosen/rejected pairs before training.",
    },
    "distillation-sft": {
        "title": "SLM Synthetic Distillation SFT",
        "summary": "Synthetic response-distillation dataset containing prompt-response examples generated with a teacher model.",
        "dataset_type": "response distillation",
        "unit_label": "Total rows",
        "schema": """{
  "id": "string",
  "prompt": "string",
  "reasoning": null,
  "response": "string",
  "metadata": {
    "signal": "string",
    "category": "string",
    "difficulty": 1,
    "template_family": "string",
    "eval_family": "string | null"
  }
}""",
        "schema_note": "`reasoning` is present for schema compatibility and is currently always `null`.",
        "intended_use": "Use this dataset for supervised fine-tuning experiments that distill teacher responses into a smaller model.",
        "limitations": "This dataset is synthetic. Prompt diversity and response quality should be inspected before production training.",
    },
    "distillation-dpo": {
        "title": "SLM Synthetic Distillation DPO",
        "summary": "Synthetic distillation preference dataset containing chosen and rejected teacher-response pairs.",
        "dataset_type": "distillation preference optimization",
        "unit_label": "Total pairs",
        "schema": """{
  "id": "string",
  "prompt": [
    {"role": "user", "content": "string"}
  ],
  "chosen": [
    {"role": "assistant", "content": "string"}
  ],
  "rejected": [
    {"role": "assistant", "content": "string"}
  ],
  "metadata": {
    "preference_dimension": "string",
    "category": "string",
    "difficulty": 1,
    "template_family": "string",
    "eval_family": "string | null",
    "failure_mode": "string",
    "failure_mode_source": "generation_intent"
  }
}""",
        "intended_use": "Use this dataset for DPO-style alignment after response distillation.",
        "limitations": "This dataset is synthetic. Code-generation and refusal-style pairs should be inspected before training.",
    },
}


CARD_KINDS = CARD_SPECS


def build_dataset_card(
    kind: str,
    *,
    total: int | None = None,
    family: str | None = None,
    signals: Iterable[str] | None = None,
    teacher_model: str | None = None,
    model_roles: Mapping[str, str] | None = None,
    distribution: Mapping[str, int] | None = None,
    title: str | None = None,
    language: str = "English",
) -> str:
    """Build a short, consumer-facing Hugging Face dataset card.

    The card describes the dataset artifact, not the generation job. It must not
    expose run IDs, provider/routing details, planned/accepted/rejected counters,
    batch/concurrency/cost settings, or local filesystem paths.
    """

    if kind not in CARD_SPECS:
        allowed = ", ".join(sorted(CARD_SPECS))
        raise ValueError(f"unknown dataset-card kind {kind!r}; expected one of: {allowed}")

    spec = CARD_SPECS[kind]
    clean_signals = _clean_list(signals)
    lines = [
        build_hf_data_files_yaml(kind=kind, signals=clean_signals).rstrip(),
        "",
        f"# {title or spec['title']}",
        "",
        "## Summary",
        "",
        spec["summary"],
        "",
        "## Dataset",
        "",
        f"- Dataset type: `{spec['dataset_type']}`",
    ]

    if total is not None:
        lines.append(f"- {spec['unit_label']}: `{total:,}`")
    if family:
        lines.append(f"- Family: `{family}`")
    if clean_signals:
        label = {
            "sft": "Task families",
            "dpo": "Preference dimensions",
            "distillation-dpo": "Preference dimensions",
        }.get(kind, "Signals")
        lines.append(f"- {label}: `{', '.join(clean_signals)}`")
    lines.append(f"- Language: {language}")

    clean_distribution = _clean_distribution(distribution)
    distribution_total = sum(value for _, value in clean_distribution)
    if total is not None and clean_distribution and distribution_total != total:
        raise ValueError(
            f"dataset-card distribution total {distribution_total} does not match "
            f"the published total {total} for {kind}"
        )
    if clean_distribution:
        heading, key_label, value_label = _distribution_labels(kind)
        lines.extend(["", f"### {heading}", "", f"| {key_label} | {value_label} |", "|---|---:|"])
        for key, value in clean_distribution:
            lines.append(f"| {key} | {value:,} |")
        lines.append(f"| **Total** | **{distribution_total:,}** |")

    # Generation-model provenance is useful for distillation products because
    # teacher/pair provenance is part of what those datasets represent. Generic
    # SFT/DPO cards describe the dataset artifact itself and intentionally omit
    # internal generation/judge/reviewer model choices.
    show_model_provenance = kind in {"distillation-sft", "distillation-dpo"}
    clean_model_roles = _clean_model_roles(model_roles)
    if show_model_provenance and clean_model_roles:
        lines.extend(["", "## Generation Models", ""])
        for label, model in clean_model_roles:
            lines.append(f"- {label}: `{model}`")
    elif show_model_provenance and teacher_model:
        lines.extend(["", "## Generation Models", "", f"- Teacher model: `{teacher_model}`"])

    lines.extend(["", "## Schema", "", "```json", spec["schema"], "```"])
    schema_note = spec.get("schema_note")
    if schema_note:
        lines.extend(["", schema_note])

    lines.extend(
        [
            "",
            "## Intended Use",
            "",
            spec["intended_use"],
            "",
            "## Limitations",
            "",
            spec["limitations"],
            "",
        ]
    )
    return "\n".join(lines)


def write_dataset_card(
    kind: str,
    run_dir: str | Path,
    *,
    title: str | None = None,
    total: int | None = None,
    family: str | None = None,
    signals: Iterable[str] | None = None,
    teacher_model: str | None = None,
    model_roles: Mapping[str, str] | None = None,
    distribution: Mapping[str, int] | None = None,
) -> Path:
    """Write README.md into a generation run directory."""

    run_path = Path(run_dir)
    metadata = _metadata_from_run_dir(kind=kind, run_dir=run_path)

    if total is None:
        total = metadata.get("total")
    if signals is None:
        signals = metadata.get("signals")
    if teacher_model is None:
        teacher_model = metadata.get("teacher_model")
    if model_roles is None:
        model_roles = metadata.get("model_roles")
    if distribution is None:
        distribution = metadata.get("distribution")

    run_path.mkdir(parents=True, exist_ok=True)
    readme_path = run_path / "README.md"
    readme_path.write_text(
        build_dataset_card(
            kind,
            title=title,
            total=total,
            family=family,
            signals=signals,
            teacher_model=teacher_model,
            model_roles=model_roles,
            distribution=distribution,
        ),
        encoding="utf-8",
    )
    return readme_path


def _metadata_from_run_dir(*, kind: str, run_dir: Path) -> dict[str, Any]:
    manifest: dict[str, Any] = {}
    try:
        _, manifest = load_run_manifest(run_dir=run_dir, kind=kind)
    except FileNotFoundError:
        pass

    stats = None
    try:
        stats = public_dataset_stats(kind=kind, run_dir=run_dir)
    except FileNotFoundError:
        pass

    distribution = _distribution_from_manifest(kind=kind, manifest=manifest)
    total = _total_from_manifest(kind=kind, manifest=manifest)
    if stats is not None:
        public_distribution = stats.metadata_counts or stats.file_counts
        if total is not None and total != stats.total:
            raise ValueError(
                f"manifest total {total} does not match public JSONL count "
                f"{stats.total} for {kind}; normalize manifests before building the card"
            )
        if distribution and distribution != public_distribution:
            raise ValueError(
                "manifest published distribution does not match public JSONL counts "
                f"for {kind}; normalize manifests before building the card"
            )
        total = stats.total
        distribution = public_distribution

    signals = _signals_from_manifest(manifest)
    if not signals and distribution:
        signals = sorted(distribution)
    if not signals:
        signals = (
            _signals_from_dataset_dir(run_dir / "datasets")
            or _signals_from_dataset_dir(run_dir / "data")
        )

    return {
        "total": total,
        "teacher_model": _clean_string(manifest.get("teacher_model")),
        "model_roles": _model_roles_from_manifest(kind=kind, manifest=manifest),
        "signals": signals,
        "distribution": distribution,
    }


def _distribution_from_manifest(
    *, kind: str, manifest: Mapping[str, Any]
) -> dict[str, int]:
    metadata = manifest.get("metadata")
    if not isinstance(metadata, Mapping):
        metadata = {}
    field = {
        "pretrain": "published_signal_counts",
        "sft": "published_family_counts",
        "dpo": "published_dimension_counts",
        "distillation-sft": "published_signal_counts",
        "distillation-dpo": "published_dimension_counts",
    }[kind]
    value = metadata.get(field)
    if isinstance(value, Mapping):
        counts = {
            str(key).strip(): int(count)
            for key, count in value.items()
            if isinstance(key, str)
            and key.strip()
            and isinstance(count, int)
            and not isinstance(count, bool)
            and count >= 0
        }
        if counts:
            return dict(sorted(counts.items()))

    counts: dict[str, int] = {}
    entries = manifest.get("datasets")
    if not isinstance(entries, list):
        entries = manifest.get("data")
    if not isinstance(entries, list):
        return counts
    for entry in entries:
        if not isinstance(entry, Mapping):
            continue
        key = (
            _clean_string(entry.get("signal"))
            or _clean_string(entry.get("family"))
            or _clean_string(entry.get("preference_dimension"))
        )
        count = entry.get("row_count")
        if key and isinstance(count, int) and not isinstance(count, bool) and count >= 0:
            counts[key] = count
    return dict(sorted(counts.items()))


def _total_from_manifest(*, kind: str, manifest: Mapping[str, Any]) -> int | None:
    field_by_kind = {
        "pretrain": "total_records",
        "sft": "total_rows",
        "dpo": "total_pairs",
        "distillation-sft": "total_rows",
        "distillation-dpo": "total_pairs",
    }
    field = field_by_kind[kind]
    value = manifest.get(field)
    if isinstance(value, int) and value >= 0:
        return value
    if field == "total_records":
        fallback = manifest.get("total_rows")
        if isinstance(fallback, int) and fallback >= 0:
            return fallback
    return None


def _signals_from_manifest(manifest: Mapping[str, Any]) -> list[str]:
    pretrain_signals = manifest.get("signals")
    if isinstance(pretrain_signals, Mapping):
        values = [key for key in pretrain_signals if isinstance(key, str) and key.strip()]
        if values:
            return sorted(set(values))

    for field in ("signals", "families", "preference_dimensions"):
        raw = manifest.get(field)
        if isinstance(raw, list):
            values = [value for value in raw if isinstance(value, str) and value.strip()]
            if values:
                return sorted(set(values))

    datasets = manifest.get("datasets")
    if not isinstance(datasets, list):
        datasets = manifest.get("data")
    if not isinstance(datasets, list):
        return []

    values: list[str] = []
    for dataset in datasets:
        if not isinstance(dataset, Mapping):
            continue
        value = (
            _clean_string(dataset.get("signal"))
            or _clean_string(dataset.get("family"))
            or _clean_string(dataset.get("preference_dimension"))
        )
        if value:
            values.append(value)
    return sorted(set(values))


def _signals_from_dataset_dir(dataset_dir: Path) -> list[str]:
    if not dataset_dir.exists():
        return []
    return sorted(path.stem.split(".batch", 1)[0] for path in dataset_dir.glob("*.jsonl") if ".batch" not in path.stem)


def _model_roles_from_manifest(*, kind: str, manifest: Mapping[str, Any]) -> dict[str, str]:
    metadata = manifest.get("metadata")
    if not isinstance(metadata, Mapping):
        metadata = {}

    role_fields = {
        "distillation-sft": (
            ("Derivation model", "derivation_model"),
            ("Task model", "task_model"),
            ("Teacher response model", "answer_model"),
            ("Judge model", "judge_model"),
            ("Reviewer model", "reviewer_model"),
        ),
        "distillation-dpo": (
            ("Derivation model", "derivation_model"),
            ("Task model", "task_model"),
            ("Pair model", "pair_model"),
            ("Judge model", "judge_model"),
            ("Reviewer model", "reviewer_model"),
        ),
    }.get(kind, ())

    roles: dict[str, str] = {}
    for label, field in role_fields:
        value = _clean_string(metadata.get(field))
        if value:
            roles[label] = value

    if kind == "distillation-sft" and "Teacher response model" not in roles:
        value = _clean_string(manifest.get("teacher_model"))
        if value:
            roles["Teacher response model"] = value
    if kind == "distillation-dpo" and "Pair model" not in roles:
        value = _clean_string(manifest.get("teacher_model"))
        if value:
            roles["Pair model"] = value
    return roles


def _clean_distribution(
    distribution: Mapping[str, int] | None,
) -> list[tuple[str, int]]:
    if not isinstance(distribution, Mapping):
        return []
    values: list[tuple[str, int]] = []
    for key, count in distribution.items():
        clean_key = _clean_string(key)
        if (
            clean_key
            and isinstance(count, int)
            and not isinstance(count, bool)
            and count >= 0
        ):
            values.append((clean_key, count))
    return sorted(values)


def _distribution_labels(kind: str) -> tuple[str, str, str]:
    return {
        "pretrain": ("Signal Distribution", "Signal", "Records"),
        "sft": ("Task Family Distribution", "Task family", "Rows"),
        "dpo": ("Preference Dimension Distribution", "Preference dimension", "Pairs"),
        "distillation-sft": ("Signal Distribution", "Signal", "Rows"),
        "distillation-dpo": (
            "Preference Dimension Distribution",
            "Preference dimension",
            "Pairs",
        ),
    }[kind]


def _clean_model_roles(model_roles: Mapping[str, str] | None) -> list[tuple[str, str]]:
    if not isinstance(model_roles, Mapping):
        return []
    values: list[tuple[str, str]] = []
    for label, model in model_roles.items():
        clean_label = _clean_string(label)
        clean_model = _clean_string(model)
        if clean_label and clean_model:
            values.append((clean_label, clean_model))
    return values


def _clean_list(values: Iterable[str] | None) -> list[str]:
    if values is None:
        return []
    return sorted({value.strip() for value in values if isinstance(value, str) and value.strip()})


def _clean_string(value: Any) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _build_cli(args: argparse.Namespace) -> int:
    path = write_dataset_card(
        args.kind,
        args.run_dir,
        title=args.title,
        total=args.total,
        family=args.family,
        signals=args.signals,
        teacher_model=args.teacher_model,
    )
    print(f"[cards] wrote {path}")
    return 0


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build standard generation dataset cards.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="write README.md for a generation run")
    build_parser.add_argument("--kind", choices=sorted(CARD_SPECS), required=True)
    build_parser.add_argument("--run-dir", required=True)
    build_parser.add_argument("--title", default=None)
    build_parser.add_argument("--total", type=int, default=None)
    build_parser.add_argument("--family", default=None)
    build_parser.add_argument("--signals", nargs="*", default=None)
    build_parser.add_argument("--teacher-model", default=None)
    build_parser.set_defaults(func=_build_cli)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(cli())
