"""Shared Hugging Face dataset-card generation for public dataset outputs."""

from __future__ import annotations

import argparse
import json
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any


HF_DATA_FILES_YAML = """---
configs:
- config_name: default
  data_files:
  - split: train
    path: data/*.jsonl
---
"""


CARD_SPECS: dict[str, dict[str, str]] = {
    "pretrain": {
        "title": "SLM Synthetic Pretrain",
        "summary": "Synthetic pretraining records generated by `slm-synthetic-data`.",
        "dataset_type": "pretraining text",
        "unit_label": "Total records",
        "schema": """{
  "id": "string",
  "text": "string",
  "metadata": {}
}""",
        "intended_use": "Use this dataset for small-language-model pretraining or data-mixing experiments.",
        "limitations": "This dataset is synthetic and should be filtered, mixed, and inspected before training. It is not a benchmark.",
    },
    "sft": {
        "title": "SLM Synthetic SFT",
        "summary": "Synthetic supervised fine-tuning dataset containing prompt-response conversations.",
        "dataset_type": "supervised fine-tuning",
        "unit_label": "Total rows",
        "schema": """{
  "id": "string",
  "messages": [
    {"role": "user", "content": "string"},
    {"role": "assistant", "content": "string"}
  ],
  "metadata": {
    "category": "string",
    "difficulty": 1,
    "template_family": "string",
    "eval_family": "string"
  }
}""",
        "intended_use": "Use this dataset for supervised fine-tuning experiments.",
        "limitations": "This dataset is synthetic. Inspect samples before training and do not use it as an evaluation benchmark.",
    },
    "dpo": {
        "title": "SLM Synthetic DPO",
        "summary": "Synthetic preference-pair dataset containing chosen and rejected assistant responses.",
        "dataset_type": "preference optimization",
        "unit_label": "Total pairs",
        "schema": """{
  "id": "string",
  "prompt": [
    {"role": "user", "content": "string"}
  ],
  "chosen": [
    {"role": "assistant", "content": "string"}
  ],
  "rejected": [
    {"role": "assistant", "content": "string"}
  ],
  "metadata": {
    "category": "string",
    "difficulty": 1,
    "template_family": "string",
    "eval_family": "string",
    "failure_mode": "string"
  }
}""",
        "intended_use": "Use this dataset for DPO-style preference optimization experiments.",
        "limitations": "This dataset is synthetic and encodes targeted preference behavior. Inspect chosen/rejected pairs before training.",
    },
    "distillation-sft": {
        "title": "SLM Synthetic Distillation SFT",
        "summary": "Synthetic response-distillation dataset containing prompt-response examples generated with a teacher model.",
        "dataset_type": "response distillation",
        "unit_label": "Total rows",
        "schema": """{
  "id": "string",
  "prompt": "string",
  "reasoning": null,
  "response": "string",
  "metadata": {
    "category": "string",
    "difficulty": 1,
    "template_family": "string",
    "eval_family": "string | null"
  }
}""",
        "schema_note": "`reasoning` is present for schema compatibility and is currently always `null`.",
        "intended_use": "Use this dataset for supervised fine-tuning experiments that distill teacher responses into a smaller model.",
        "limitations": "This dataset is synthetic. Prompt diversity and response quality should be inspected before production training.",
    },
    "distillation-dpo": {
        "title": "SLM Synthetic Distillation DPO",
        "summary": "Synthetic distillation preference dataset containing chosen and rejected teacher-response pairs.",
        "dataset_type": "distillation preference optimization",
        "unit_label": "Total pairs",
        "schema": """{
  "id": "string",
  "prompt": [
    {"role": "user", "content": "string"}
  ],
  "chosen": [
    {"role": "assistant", "content": "string"}
  ],
  "rejected": [
    {"role": "assistant", "content": "string"}
  ],
  "metadata": {
    "category": "string",
    "template_family": "string",
    "eval_family": "string",
    "failure_mode": "string"
  }
}""",
        "intended_use": "Use this dataset for DPO-style alignment after response distillation.",
        "limitations": "This dataset is synthetic. Code-generation and refusal-style pairs should be inspected before training.",
    },
}


CARD_KINDS = CARD_SPECS


def build_dataset_card(
    kind: str,
    *,
    total: int | None = None,
    family: str | None = None,
    signals: Iterable[str] | None = None,
    teacher_model: str | None = None,
    title: str | None = None,
    language: str = "English",
) -> str:
    """Build a short, consumer-facing Hugging Face dataset card.

    The card describes the dataset artifact, not the generation job. It must not
    expose run IDs, provider/routing details, planned/accepted/rejected counters,
    batch/concurrency/cost settings, or local filesystem paths.
    """

    if kind not in CARD_SPECS:
        allowed = ", ".join(sorted(CARD_SPECS))
        raise ValueError(f"unknown dataset-card kind {kind!r}; expected one of: {allowed}")

    spec = CARD_SPECS[kind]
    lines = [
        HF_DATA_FILES_YAML.rstrip(),
        "",
        f"# {title or spec['title']}",
        "",
        "## Summary",
        "",
        spec["summary"],
        "",
        "## Dataset",
        "",
        f"- Dataset type: `{spec['dataset_type']}`",
    ]

    if total is not None:
        lines.append(f"- {spec['unit_label']}: `{total}`")
    if family:
        lines.append(f"- Family: `{family}`")
    clean_signals = _clean_list(signals)
    if clean_signals:
        lines.append(f"- Signals: `{', '.join(clean_signals)}`")
    if teacher_model:
        lines.append(f"- Teacher model: `{teacher_model}`")
    lines.append(f"- Language: {language}")

    lines.extend(["", "## Schema", "", "```json", spec["schema"], "```"])
    schema_note = spec.get("schema_note")
    if schema_note:
        lines.extend(["", schema_note])

    lines.extend(
        [
            "",
            "## Intended Use",
            "",
            spec["intended_use"],
            "",
            "## Limitations",
            "",
            spec["limitations"],
            "",
        ]
    )
    return "\n".join(lines)


def write_dataset_card(
    kind: str,
    run_dir: str | Path,
    *,
    title: str | None = None,
    total: int | None = None,
    family: str | None = None,
    signals: Iterable[str] | None = None,
    teacher_model: str | None = None,
) -> Path:
    """Write README.md into a generation run directory."""

    run_path = Path(run_dir)
    metadata = _metadata_from_run_dir(kind=kind, run_dir=run_path)

    if total is None:
        total = metadata.get("total")
    if signals is None:
        signals = metadata.get("signals")
    if teacher_model is None:
        teacher_model = metadata.get("teacher_model")

    run_path.mkdir(parents=True, exist_ok=True)
    readme_path = run_path / "README.md"
    readme_path.write_text(
        build_dataset_card(
            kind,
            title=title,
            total=total,
            family=family,
            signals=signals,
            teacher_model=teacher_model,
        ),
        encoding="utf-8",
    )
    return readme_path


def _metadata_from_run_dir(*, kind: str, run_dir: Path) -> dict[str, Any]:
    manifest_path = run_dir / "manifests" / f"{run_dir.name}.manifest.json"
    manifest: dict[str, Any] = {}
    if manifest_path.is_file():
        try:
            value = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            value = {}
        if isinstance(value, Mapping):
            manifest = dict(value)

    return {
        "total": _total_from_manifest(kind=kind, manifest=manifest),
        "teacher_model": _clean_string(manifest.get("teacher_model")),
        "signals": _signals_from_manifest(manifest) or _signals_from_dataset_dir(run_dir / "datasets"),
    }


def _total_from_manifest(*, kind: str, manifest: Mapping[str, Any]) -> int | None:
    field_by_kind = {
        "pretrain": "total_records",
        "sft": "total_rows",
        "dpo": "total_pairs",
        "distillation-sft": "total_rows",
        "distillation-dpo": "total_pairs",
    }
    field = field_by_kind[kind]
    value = manifest.get(field)
    if isinstance(value, int) and value >= 0:
        return value
    if field == "total_records":
        fallback = manifest.get("total_rows")
        if isinstance(fallback, int) and fallback >= 0:
            return fallback
    return None


def _signals_from_manifest(manifest: Mapping[str, Any]) -> list[str]:
    datasets = manifest.get("datasets")
    if not isinstance(datasets, list):
        return []

    values: list[str] = []
    for dataset in datasets:
        if not isinstance(dataset, Mapping):
            continue
        value = _clean_string(dataset.get("signal")) or _clean_string(dataset.get("family"))
        if value:
            values.append(value)
    return sorted(set(values))


def _signals_from_dataset_dir(dataset_dir: Path) -> list[str]:
    if not dataset_dir.exists():
        return []
    return sorted(path.stem.split(".batch", 1)[0] for path in dataset_dir.glob("*.jsonl") if ".batch" not in path.stem)


def _clean_list(values: Iterable[str] | None) -> list[str]:
    if values is None:
        return []
    return sorted({value.strip() for value in values if isinstance(value, str) and value.strip()})


def _clean_string(value: Any) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _build_cli(args: argparse.Namespace) -> int:
    path = write_dataset_card(
        args.kind,
        args.run_dir,
        title=args.title,
        total=args.total,
        family=args.family,
        signals=args.signals,
        teacher_model=args.teacher_model,
    )
    print(f"[cards] wrote {path}")
    return 0


def cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build standard generation dataset cards.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="write README.md for a generation run")
    build_parser.add_argument("--kind", choices=sorted(CARD_SPECS), required=True)
    build_parser.add_argument("--run-dir", required=True)
    build_parser.add_argument("--title", default=None)
    build_parser.add_argument("--total", type=int, default=None)
    build_parser.add_argument("--family", default=None)
    build_parser.add_argument("--signals", nargs="*", default=None)
    build_parser.add_argument("--teacher-model", default=None)
    build_parser.set_defaults(func=_build_cli)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(cli())
