"""DPO synthetic row validation."""

from slm_synth.dpo.batches import (
    DPO_BATCH_RESPONSE_SCHEMA,
    build_dpo_teacher_request_items,
    build_dpo_teacher_request_object,
    render_dpo_batch_prompt,
    validate_dpo_batch_response,
)
from slm_synth.dpo.generation import (
    DPOLLMBatchResult,
    build_openrouter_backend,
    generate_llm_batch,
    generate_llm_batch_from_files,
    generate_teacher_batch_response,
    materialize_llm_batch,
    materialize_llm_batch_from_files,
    read_specs_jsonl,
    read_teacher_response_json,
)
from slm_synth.dpo.io import read_jsonl, write_jsonl
from slm_synth.dpo.manifest import build_manifest_payload, write_manifest, write_run_manifest
from slm_synth.dpo.report import build_coverage_report, write_coverage_report
from slm_synth.dpo.runs import (
    DPOLLMRunResult,
    DPOSeedFamilyRunResult,
    DPOSeedRunResult,
    generate_llm_run,
    materialize_seed_dataset,
    materialize_seed_run,
    resolve_spec_families,
    resolve_seed_families,
)
from slm_synth.dpo.schema import validate_dpo_row, validate_message_list
from slm_synth.dpo.seeds import (
    DPO_SEED_FAMILIES,
    build_ai_concept_explanation_rows,
    build_answer_only_arithmetic_rows,
    build_capital_city_qa_rows,
    build_clear_sky_color_qa_rows,
    build_code_explanation_no_code_rows,
    build_code_expression_result_rows,
    build_code_generation_function_rows,
    build_direct_division_rows,
    build_direct_subtraction_rows,
    build_function_completion_body_only_rows,
    build_list_exact_n_items_rows,
    build_private_or_unverifiable_company_fact_rows,
    build_repeat_exact_n_times_rows,
    build_seed_rows,
)
from slm_synth.dpo.spec_builders import (
    DPO_SPEC_FAMILIES,
    build_and_write_specs,
    build_specs,
    write_specs_jsonl,
)
from slm_synth.dpo.specs import teacher_visible_dpo_spec, validate_dpo_spec

__all__ = [
    "DPO_BATCH_RESPONSE_SCHEMA",
    "DPOLLMRunResult",
    "DPO_SPEC_FAMILIES",
    "DPOLLMBatchResult",
    "DPO_SEED_FAMILIES",
    "DPOSeedFamilyRunResult",
    "DPOSeedRunResult",
    "build_ai_concept_explanation_rows",
    "build_answer_only_arithmetic_rows",
    "build_capital_city_qa_rows",
    "build_coverage_report",
    "build_clear_sky_color_qa_rows",
    "build_code_explanation_no_code_rows",
    "build_code_expression_result_rows",
    "build_code_generation_function_rows",
    "build_direct_division_rows",
    "build_direct_subtraction_rows",
    "build_function_completion_body_only_rows",
    "build_list_exact_n_items_rows",
    "build_manifest_payload",
    "build_private_or_unverifiable_company_fact_rows",
    "build_repeat_exact_n_times_rows",
    "build_seed_rows",
    "build_and_write_specs",
    "build_specs",
    "build_openrouter_backend",
    "build_dpo_teacher_request_items",
    "build_dpo_teacher_request_object",
    "generate_llm_batch",
    "generate_llm_batch_from_files",
    "generate_llm_run",
    "generate_teacher_batch_response",
    "materialize_seed_dataset",
    "materialize_seed_run",
    "materialize_llm_batch",
    "materialize_llm_batch_from_files",
    "read_jsonl",
    "read_specs_jsonl",
    "read_teacher_response_json",
    "render_dpo_batch_prompt",
    "resolve_spec_families",
    "resolve_seed_families",
    "teacher_visible_dpo_spec",
    "validate_dpo_batch_response",
    "validate_dpo_row",
    "validate_dpo_spec",
    "validate_message_list",
    "write_jsonl",
    "write_specs_jsonl",
    "write_coverage_report",
    "write_manifest",
    "write_run_manifest",
]
