"""Independent finite prompt inventory for generic DPO generation.

These prompts are authored for preference comparison.  They deliberately do
not import or transform SFT source specs.
"""

from __future__ import annotations

from typing import Any


def _source(
    source_key: str,
    instruction: str,
    variables: dict[str, Any],
    *,
    task_family: str,
    failure_mode: str,
    interaction_modes: tuple[str, ...] = ("single_turn",),
    output_mode: str = "free_text",
    context_mode: str = "self_contained",
    difficulty: int = 2,
    template_family: str,
    holdout_key: dict[str, Any] | None = None,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "source_key": source_key,
        "instruction": instruction,
        "variables": variables,
        "failure_mode": failure_mode,
        "metadata": {
            "task_family": task_family,
            "interaction_modes": list(interaction_modes),
            "output_mode": output_mode,
            "context_mode": context_mode,
            "difficulty": difficulty,
            "template_family": template_family,
        },
    }
    if holdout_key is not None:
        value["holdout_key"] = holdout_key
    return value


DPO_SOURCE_CATALOG: dict[str, tuple[dict[str, Any], ...]] = {
    "helpfulness_and_completeness": (
        _source("evacuation_checklist_coverage", "Generate a preferred and rejected answer to a request for a complete small-office evacuation checklist. The rejected answer should sound useful but omit a critical phase.", {"constraints": ["before, during, and after evacuation", "include visitors and mobility needs", "no invented local rules"]}, failure_mode="incomplete_response", output_mode="structured_json", task_family="planning_brainstorming_recommendations", template_family="coverage_gap_preference"),
        _source("recipe_substitution_tradeoffs", "Compare responses to a cook who needs substitutions for eggs and dairy; reward an answer that distinguishes binding, moisture, and flavor consequences.", {"dish": "savory breakfast muffins", "available": ["flax meal", "oat milk", "olive oil"]}, failure_mode="incomplete_response", task_family="planning_brainstorming_recommendations", template_family="constraint_complete_advice"),
        _source("lost_luggage_next_steps", "Create a preference pair for a traveler asking what to do after checked luggage fails to arrive. The chosen answer must sequence immediate and follow-up actions without promising reimbursement.", {"facts": ["bag tag retained", "airline desk closed", "medication is not in bag"]}, failure_mode="incomplete_response", task_family="everyday_conversation", template_family="actionable_support_preference"),
        _source("handbook_question_full_answer", "Produce two grounded answers to the employee's question. Prefer the response that answers both eligibility and timing while acknowledging the missing employment status.", {"passage": "Full-time employees may apply after ninety days. Part-time employees may apply after 180 days. Contractors are ineligible.", "question": "When can I apply?"}, failure_mode="incomplete_response", context_mode="supplied_passage", task_family="grounded_qa_and_reading", template_family="multi_part_answer_preference"),
        _source("bug_report_reproduction", "Create two replies to a bug report. Prefer the one that gives a minimal diagnostic path and asks only information needed to reproduce the issue.", {"report": "The dashboard goes blank after I change the date range."}, failure_mode="incomplete_response", task_family="programming", template_family="diagnostic_completeness_preference"),
        _source("meeting_request_response", "Compare two replies to a meeting request that conflicts with a stated deadline. Prefer the response that addresses the conflict, offers workable alternatives, and confirms the next action.", {"request": "Can we meet for an hour at 4 PM?", "constraint": "the report must be submitted by 4:30 PM"}, failure_mode="incomplete_response", task_family="everyday_conversation", template_family="constraint_resolving_reply"),
        _source("plant_care_diagnosis", "Compare two answers to a novice gardener. Prefer the response that covers the most likely causes, a safe diagnostic order, and signs requiring a different action.", {"symptom": "lower leaves yellowing while soil remains wet"}, failure_mode="incomplete_response", task_family="everyday_conversation", template_family="diagnostic_branch_coverage"),
        _source("reading_response_two_parts", "Generate two answers to a two-part reading question. Prefer the response that answers both parts with separate evidence.", {"passage": "The ferry stopped winter service because ice damaged the eastern dock. A bus shuttle will operate until repairs finish.", "question": "Why did ferry service stop, and what replacement is offered?"}, failure_mode="incomplete_response", context_mode="supplied_passage", task_family="grounded_qa_and_reading", template_family="two_part_grounded_response"),
        _source("budget_plan_contingency", "Create two budget plans for a community workshop. Prefer the one that allocates required costs and includes a realistic contingency without exceeding the cap.", {"cap": "$600", "required": ["room $180", "materials $220", "insurance $75"]}, failure_mode="incomplete_response", output_mode="table", task_family="planning_brainstorming_recommendations", template_family="complete_budget_preference"),
    ),
    "factual_accuracy": (
        _source("warehouse_percentage", "Generate a preference pair for the quantitative question. The chosen response must calculate and independently verify the percentage; the rejected response should make a plausible arithmetic error.", {"question": "A warehouse inspected 240 packages and found 18 damaged. What percentage were damaged?", "verified_answer": "7.5 percent"}, failure_mode="wrong_numeric_answer", task_family="applied_math_and_reasoning", template_family="verified_numeric_preference", holdout_key={"kind": "percentage", "values": [240, 18]}),
        _source("version_history_fact", "Compare answers using only the revision history. Prefer the answer that attributes each change to the correct version and person.", {"passage": "Version 1 was drafted by Imani. Version 2 changed the delivery date and was approved by Chen. Version 3 fixed a spelling error and was approved by Imani.", "question": "Who approved the delivery-date change?"}, failure_mode="wrong_factual_answer", context_mode="supplied_passage", task_family="grounded_qa_and_reading", template_family="attribution_accuracy_preference"),
        _source("sql_null_semantics", "Create a preference pair explaining whether the query includes customers with no orders. Reward technically accurate SQL null and join semantics.", {"query": "SELECT c.id, COUNT(o.id) FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id"}, failure_mode="unsupported_claim", output_mode="code", context_mode="supplied_passage", difficulty=3, task_family="programming", template_family="technical_explanation_accuracy"),
        _source("study_claim_scope", "Produce two summaries of the study note. Prefer the one that preserves observational design and avoids a causal claim.", {"study": "A survey found commuters who reported cycling at least twice weekly also reported higher life satisfaction. Participants selected their travel mode; no intervention occurred."}, failure_mode="unsupported_claim", output_mode="concise", context_mode="supplied_passage", task_family="summarization", template_family="evidence_scope_preference"),
        _source("calendar_constraint_answer", "Generate two solutions to the scheduling puzzle. The chosen answer must satisfy every constraint and show a quick check.", {"items": ["review", "backup", "deployment", "announcement"], "constraints": ["backup before deployment", "review before announcement", "deployment after review"]}, failure_mode="wrong_factual_answer", difficulty=3, task_family="applied_math_and_reasoning", template_family="constraint_correctness_preference"),
        _source("unit_conversion", "Create two solutions to a medication-free unit conversion problem. Prefer the response with correct dimensional cancellation and a magnitude check.", {"question": "Convert 3.6 kilometers per hour to meters per second.", "verified_answer": "1 meter per second"}, failure_mode="wrong_numeric_answer", task_family="applied_math_and_reasoning", template_family="dimensional_analysis_preference"),
        _source("timeline_date_inference", "Compare two answers derived from the timeline. Prefer the only date consistent with all stated offsets.", {"facts": ["inspection was two days after delivery", "delivery was Monday 6 July", "report followed inspection by one day"]}, failure_mode="wrong_factual_answer", task_family="applied_math_and_reasoning", template_family="timeline_inference_preference"),
        _source("api_return_type_fact", "Generate two explanations of the API contract. Prefer the response that correctly distinguishes an empty result from an error.", {"contract": "Returns an empty list when no matches exist; raises PermissionError only when the caller lacks access."}, failure_mode="unsupported_claim", context_mode="supplied_passage", task_family="programming", template_family="contract_semantics_accuracy"),
        _source("ratio_table_check", "Create two interpretations of the table. Prefer the response that calculates rates using the correct denominators rather than comparing raw totals.", {"table": [{"site": "north", "success": 45, "attempts": 50}, {"site": "south", "success": 72, "attempts": 90}]}, failure_mode="wrong_numeric_answer", output_mode="table", task_family="applied_math_and_reasoning", template_family="denominator_accuracy_preference"),
    ),
    "instruction_adherence": (
        _source("exact_json_fields", "Generate two answers to an extraction request requiring exactly four JSON keys and no prose. The rejected response should violate the requested surface despite extracting correct facts.", {"text": "Case 81 was opened by Noor on 7 April and remains pending.", "required_keys": ["case_id", "owner", "opened", "status"]}, failure_mode="format_violation", output_mode="structured_json", context_mode="supplied_passage", task_family="classification_and_extraction", template_family="strict_format_preference"),
        _source("preserve_uncertainty_rewrite", "Create a preference pair for rewriting the statement in plain language while retaining both uncertainty markers and staying under forty words.", {"source": "Preliminary observations suggest the change may be associated with lower latency, but the sample is limited and confounding has not been assessed."}, failure_mode="instruction_violation", output_mode="exact_constraints", context_mode="supplied_passage", task_family="rewriting_and_editing", template_family="constraint_retention_preference"),
        _source("forbidden_word_story", "Compare two micro-stories under explicit lexical and length constraints. The chosen response must satisfy them without sounding like a checklist.", {"prompt": "Write 120–150 words about a stranded astronomer.", "forbidden": ["star", "planet", "alone"], "required": "end with a question"}, failure_mode="instruction_violation", output_mode="exact_constraints", task_family="creative_writing", template_family="creative_constraint_preference"),
        _source("three_option_plan", "Produce a chosen and rejected recommendation where the user requested exactly three options, one tradeoff each, and no final selection.", {"goal": "reduce noise in an open office", "budget": "no construction"}, failure_mode="instruction_violation", output_mode="exact_constraints", task_family="planning_brainstorming_recommendations", template_family="cardinality_instruction_preference"),
        _source("python_signature_contract", "Generate two Python solutions. Prefer the one that preserves the required function signature, raises the specified exception, and contains code only.", {"signature": "def median(values: list[float]) -> float", "empty_behavior": "raise ValueError"}, failure_mode="code_includes_explanation", output_mode="code", task_family="programming", template_family="code_contract_preference"),
        _source("summary_heading_contract", "Compare two summaries under a required heading schema. Prefer the response using exactly the requested headings and placing uncertainty only in the open-questions section.", {"headings": ["Decision", "Owner", "Open questions"], "notes": "Proceed with pilot; Ren owns setup; final sample size undecided."}, failure_mode="format_violation", output_mode="exact_constraints", context_mode="supplied_passage", task_family="summarization", template_family="heading_contract_preference"),
        _source("alphabetical_table", "Generate two extraction tables. Prefer the response sorted by surname as requested, with dates preserved in ISO format.", {"note": "Zara Ng starts 4 May. Amir Cole starts 12 April. Bea Ortiz starts 30 June."}, failure_mode="instruction_violation", output_mode="table", context_mode="supplied_passage", task_family="classification_and_extraction", template_family="ordering_format_preference"),
        _source("no_external_facts", "Compare two answers to a passage question under an explicit no-external-facts instruction. Prefer the response that marks the unsupported part unknown.", {"passage": "The archive moved to Harbor Street in 1998.", "question": "When did it move and who designed the building?"}, failure_mode="instruction_violation", context_mode="supplied_passage", task_family="grounded_qa_and_reading", template_family="scope_instruction_preference"),
        _source("dialogue_turn_requirement", "Create two scripted conversations. Prefer the one with exactly three user turns, a leading system instruction, and an assistant conclusion in the final turn.", {"scenario": "clarifying dietary needs for a group meal"}, failure_mode="instruction_violation", interaction_modes=("multi_turn", "system_conditioned"), output_mode="exact_constraints", task_family="everyday_conversation", template_family="interaction_contract_preference"),
    ),
    "appropriate_detail": (
        _source("executive_status_brevity", "Compare two status summaries for an executive who requested at most four bullets. Prefer the response with decision-relevant detail and no implementation digression.", {"notes": "Launch is green; legal approval remains; load test passed; two minor UI bugs are scheduled after launch."}, failure_mode="excessive_detail", output_mode="concise", context_mode="supplied_passage", task_family="summarization", template_family="audience_calibrated_detail"),
        _source("simple_device_help", "Create two answers for a nontechnical user asking how to reconnect a wireless keyboard. Prefer concise ordered troubleshooting with one branch for failure.", {"device_facts": ["battery indicator is lit", "computer was restarted", "keyboard was previously paired"]}, failure_mode="excessive_detail", task_family="everyday_conversation", template_family="minimal_troubleshooting_detail"),
        _source("board_game_explanation", "Generate two explanations of a simple game for first-time players. Prefer enough detail to start play without edge-case overload.", {"rules": ["draw one tile", "match color or shape", "first empty rack wins"]}, failure_mode="excessive_detail", task_family="everyday_conversation", template_family="beginner_explanation_detail"),
        _source("risk_register_depth", "Compare two project-risk responses. Prefer the answer that covers the three most consequential risks with mitigations rather than listing every conceivable issue.", {"project": "moving a clinic's appointment system over one weekend", "constraints": ["no lost appointments", "paper fallback available"]}, failure_mode="excessive_detail", output_mode="table", task_family="planning_brainstorming_recommendations", template_family="priority_weighted_detail"),
        _source("code_review_scope", "Create two code-review comments. Prefer the one focused on the supplied correctness bug and a focused test, without unrelated refactoring advice.", {"code": "def first_even(xs):\n    for x in xs:\n        if x % 2:\n            return x"}, failure_mode="excessive_detail", output_mode="code", context_mode="supplied_passage", task_family="programming", template_family="review_scope_preference"),
        _source("directions_detail", "Compare two sets of walking directions for a visitor. Prefer the response containing landmarks at ambiguous turns but not a history of the neighborhood.", {"route": ["exit station east", "turn after pharmacy", "enter second courtyard"]}, failure_mode="excessive_detail", task_family="everyday_conversation", template_family="wayfinding_detail_preference"),
        _source("definition_for_child", "Generate two explanations of evaporation for a nine-year-old. Prefer one concrete example and an accurate definition without molecular-level digression.", {"example_context": "a puddle disappearing"}, failure_mode="excessive_detail", task_family="grounded_qa_and_reading", template_family="age_calibrated_explanation"),
        _source("release_note_detail", "Compare two release notes for end users. Prefer the response that states visible behavior and required action without internal ticket history.", {"change": "saved filters now sync across devices after the user signs in again"}, failure_mode="excessive_detail", output_mode="concise", task_family="rewriting_and_editing", template_family="user_facing_release_detail"),
        _source("math_solution_detail", "Create two solutions to a straightforward area problem. Prefer enough work to audit the result without explaining elementary multiplication at excessive length.", {"problem": "Find the area of an L-shape formed by a 9-by-7 rectangle with a 3-by-2 corner removed."}, failure_mode="excessive_detail", task_family="applied_math_and_reasoning", template_family="auditable_solution_detail"),
    ),
    "organization": (
        _source("conference_plan_structure", "Generate two plans for a one-day community conference. Prefer clear phases, dependencies, owners, and decision points over an unordered idea dump.", {"constraints": ["two rooms", "150 attendees", "six volunteer organizers"]}, failure_mode="poor_organization", output_mode="table", task_family="planning_brainstorming_recommendations", template_family="plan_structure_preference"),
        _source("incident_handoff_structure", "Compare two incident handoffs. Prefer the response that separates impact, timeline, actions taken, current state, and next owner.", {"incident_notes": "Checkout errors began 14:10; cache rollback at 14:32 reduced errors; root cause unknown; SRE Mara owns log analysis."}, failure_mode="poor_organization", output_mode="structured_json", context_mode="supplied_passage", task_family="summarization", template_family="operational_handoff_structure"),
        _source("tutorial_progression", "Create a preference pair for a beginner tutorial on parsing CSV in Python. Reward prerequisite-first progression and runnable steps.", {"learner": "knows variables and loops", "goal": "sum an amount column safely"}, failure_mode="poor_organization", output_mode="code", task_family="programming", template_family="pedagogical_sequence_preference"),
        _source("comparison_answer_layout", "Produce two grounded comparisons. Prefer the one that applies the same criteria to both documents and surfaces missing information separately.", {"documents": ["Lease A: twelve months, utilities included, deposit unspecified.", "Lease B: six months, utilities excluded, deposit one month."], "criteria": ["term", "utilities", "deposit"]}, failure_mode="poor_organization", output_mode="table", context_mode="multi_document", task_family="grounded_qa_and_reading", template_family="parallel_comparison_structure"),
        _source("argument_map", "Compare two explanations of a policy dispute. Prefer the answer that distinguishes claims, evidence, assumptions, and unresolved questions.", {"passage": "Residents favor later park hours for access. Nearby households cite two recent noise complaints. The proposal includes no staffing estimate."}, failure_mode="poor_organization", context_mode="supplied_passage", difficulty=3, task_family="grounded_qa_and_reading", template_family="argument_structure_preference"),
        _source("migration_runbook", "Generate two database-migration runbooks. Prefer chronological gates with prerequisites, rollback triggers, verification, and named role ownership.", {"roles": ["release lead", "database operator", "application owner"], "constraint": "fifteen-minute read-only window"}, failure_mode="poor_organization", output_mode="table", task_family="programming", template_family="runbook_sequence_preference"),
        _source("case_summary_hierarchy", "Compare two case summaries. Prefer the answer that leads with disposition, then supporting findings, then follow-up obligations.", {"facts": ["request approved conditionally", "identity check passed", "signed form still required"]}, failure_mode="poor_organization", context_mode="supplied_passage", task_family="summarization", template_family="decision_first_summary"),
        _source("lesson_plan_flow", "Generate two lesson plans for teaching fractions. Prefer a progression from concrete demonstration to guided practice to independent check.", {"duration": "forty minutes", "materials": ["paper strips", "markers"]}, failure_mode="poor_organization", output_mode="table", task_family="planning_brainstorming_recommendations", template_family="instructional_flow_preference"),
        _source("debug_report_structure", "Create two debugging reports. Prefer explicit separation of observed behavior, expected behavior, reproduction, hypothesis, and evidence.", {"symptom": "duplicate notification after reconnect", "reproduction": "disconnect network during save, then reconnect"}, failure_mode="poor_organization", task_family="programming", template_family="debug_evidence_structure"),
    ),
    "style_and_tone": (
        _source("empathetic_denial", "Generate two replies denying a refund outside policy. Prefer a calm, respectful response that states the boundary without sounding accusatory or robotic.", {"facts": ["purchase was forty-five days ago", "policy allows thirty days", "store credit may be available"]}, failure_mode="tone_mismatch", interaction_modes=("single_turn", "system_conditioned"), task_family="rewriting_and_editing", template_family="firm_empathetic_tone"),
        _source("peer_feedback_tone", "Compare two versions of feedback on a colleague's draft. Prefer specific, collaborative language over blunt judgment while preserving the substantive concern.", {"concern": "the conclusion overstates what three interviews establish"}, failure_mode="tone_mismatch", task_family="rewriting_and_editing", template_family="constructive_peer_feedback"),
        _source("grief_response_tone", "Create two responses to a friend describing a recent loss. Prefer restrained empathy that does not center the assistant or offer clichés.", {"message": "The house feels empty since my dog died last week."}, failure_mode="tone_mismatch", task_family="everyday_conversation", template_family="grief_support_tone"),
        _source("whimsical_not_silly", "Generate two short museum labels requested to feel lightly whimsical but still credible. Prefer controlled voice over jokes that undermine the artifact.", {"artifact": "a dented nineteenth-century brass telescope", "facts": ["maker unknown", "used by a coastal survey team"]}, failure_mode="tone_mismatch", output_mode="concise", context_mode="supplied_passage", task_family="creative_writing", template_family="register_control_preference"),
        _source("deescalating_roommate_reply", "Compare two replies in an ongoing roommate disagreement. Prefer language that acknowledges frustration and proposes a boundary without passive aggression.", {"prior_message": "You always leave the kitchen for me to clean."}, failure_mode="tone_mismatch", interaction_modes=("multi_turn",), task_family="everyday_conversation", template_family="deescalation_tone_preference"),
        _source("formal_plain_language", "Create two rewrites of a municipal notice for residents. Prefer plain, respectful language that remains authoritative without bureaucratic stiffness.", {"source": "Failure to effectuate removal of receptacles by the prescribed hour may result in enforcement action."}, failure_mode="tone_mismatch", context_mode="supplied_passage", task_family="rewriting_and_editing", template_family="public_notice_register_preference"),
        _source("celebratory_work_note", "Compare two congratulations notes for a teammate's promotion. Prefer warm, specific professionalism without exaggerated intimacy.", {"shared_fact": "they led the accessibility review"}, failure_mode="tone_mismatch", output_mode="concise", task_family="everyday_conversation", template_family="workplace_celebration_tone"),
        _source("uncertain_research_tone", "Generate two research-summary conclusions. Prefer appropriately cautious language matching a small exploratory sample.", {"finding": "nine of twelve interviewees preferred the revised form", "limitation": "single-site convenience sample"}, failure_mode="tone_mismatch", context_mode="supplied_passage", task_family="summarization", template_family="epistemic_tone_preference"),
        _source("childrens_adventure_voice", "Create two openings for an adventure story for ages eight to ten. Prefer vivid, accessible language without condescension or frightening gore.", {"premise": "a library book returns itself every midnight"}, failure_mode="tone_mismatch", task_family="creative_writing", template_family="age_appropriate_voice"),
    ),
    "tool_call_correctness": (
        _source("calendar_timezone_call", "Generate two assistant outputs for a calendar tool request. Prefer the JSON tool call with the correct local-to-UTC conversion and all required fields.", {"user_timezone": "America/New_York", "request": "Schedule a 30-minute review at 3 PM on 12 November 2026", "tool": "create_event(title, start_utc, duration_minutes)"}, failure_mode="incorrect_tool_call", output_mode="tool_call", task_family="planning_brainstorming_recommendations", template_family="calendar_tool_argument_preference"),
        _source("weather_location_disambiguation", "Create a preference pair where a weather tool requires a city and country. Prefer asking for clarification instead of calling the tool with an ambiguous place.", {"request": "Will it rain in Springfield tomorrow?", "tool": "forecast(city, country, date)"}, failure_mode="incorrect_tool_call", interaction_modes=("multi_turn", "tool_mediated"), output_mode="tool_call", task_family="everyday_conversation", template_family="tool_disambiguation_preference"),
        _source("database_read_only_call", "Compare two tool-call plans for answering a revenue question. Prefer the read-only query with a bounded date range and no destructive operation.", {"request": "What was net revenue last quarter?", "tools": ["query_readonly(sql)", "execute_admin(sql)"]}, failure_mode="incorrect_tool_call", interaction_modes=("single_turn", "tool_mediated"), output_mode="tool_call", task_family="classification_and_extraction", template_family="safe_database_tool_choice"),
        _source("file_search_then_read", "Generate two tool-use sequences for locating a policy clause. Prefer searching for the document before reading the exact returned identifier.", {"request": "Find the cancellation notice period in our vendor policy.", "tools": ["search_files(query)", "read_file(file_id)"]}, failure_mode="incorrect_tool_call", interaction_modes=("single_turn", "tool_mediated"), output_mode="tool_call", context_mode="multi_document", task_family="grounded_qa_and_reading", template_family="tool_sequence_preference"),
        _source("function_enum_validation", "Create a preference pair for calling a shipping quote function. Prefer arguments that respect types and allowed service values, and do not invent a postal code.", {"request": "Quote express delivery for a two-kilogram parcel; destination postal code is missing.", "tool": "quote_shipping(weight_kg: number, postal_code: string, service: standard|express)"}, failure_mode="incorrect_tool_call", interaction_modes=("multi_turn", "tool_mediated"), output_mode="tool_call", task_family="programming", template_family="function_schema_preference"),
        _source("contact_lookup_before_email", "Compare two tool-use plans for emailing a person identified only by first name. Prefer resolving the recipient before drafting or sending anything.", {"request": "Email Jordan the revised schedule.", "tools": ["search_contacts(query)", "draft_email(recipient_id, subject, body)"]}, failure_mode="incorrect_tool_call", interaction_modes=("multi_turn", "tool_mediated"), output_mode="tool_call", task_family="everyday_conversation", template_family="recipient_resolution_tool_preference"),
        _source("inventory_lookup_identifier", "Generate two inventory tool calls. Prefer the call using the supplied SKU rather than guessing a product name match.", {"request": "Check stock for SKU HZ-440 at warehouse west.", "tool": "inventory(sku, location)"}, failure_mode="incorrect_tool_call", interaction_modes=("single_turn", "tool_mediated"), output_mode="tool_call", task_family="classification_and_extraction", template_family="identifier_bound_tool_call"),
        _source("route_tool_units", "Compare two route-estimation calls. Prefer the one that sends coordinates in the documented order and requests kilometers as the user specified.", {"tool": "route(origin_lat_lon, destination_lat_lon, units)", "origin": [40.71, -74.00], "destination": [40.75, -73.98], "units": "km"}, failure_mode="incorrect_tool_call", interaction_modes=("single_turn", "tool_mediated"), output_mode="tool_call", task_family="applied_math_and_reasoning", template_family="geospatial_argument_preference"),
        _source("search_query_scope", "Create two search-tool calls for a date-bounded request. Prefer explicit terms and date filters without adding a domain the user did not name.", {"request": "Find quarterly recycling reports published in 2025.", "tool": "search(query, date_from, date_to, domain?)"}, failure_mode="incorrect_tool_call", interaction_modes=("single_turn", "tool_mediated"), output_mode="tool_call", task_family="grounded_qa_and_reading", template_family="search_scope_tool_preference"),
    ),
    "groundedness": (
        _source("permit_notice_grounding", "Generate two answers using only the permit notice. Prefer the response that separates stated facts from information the notice does not provide.", {"notice": "Applications received by 1 June will be reviewed in July. Approval is not guaranteed. Fees are listed on a separate schedule.", "question": "If I apply in May, what will it cost and will I be approved?"}, failure_mode="ungrounded_response", context_mode="supplied_passage", task_family="grounded_qa_and_reading", template_family="known_unknown_grounding"),
        _source("two_report_reconciliation", "Compare responses that reconcile two reports. Prefer explicit attribution and no invented explanation for the discrepancy.", {"documents": ["Operations report: 842 visits in March.", "Finance report: 817 paid visits in March; complimentary visits excluded."]}, failure_mode="ungrounded_response", context_mode="multi_document", task_family="summarization", template_family="source_attributed_reconciliation"),
        _source("resume_extraction_grounding", "Create two candidate JSON extractions from a résumé excerpt. Prefer null for an unstated graduation year over a plausible guess.", {"excerpt": "BSc, North College. Data analyst at Lumen Works, 2021–present.", "fields": ["degree", "school", "graduation_year", "current_employer"]}, failure_mode="ungrounded_response", output_mode="structured_json", context_mode="supplied_passage", task_family="classification_and_extraction", template_family="null_over_invention_preference"),
        _source("manual_troubleshooting_grounding", "Generate two troubleshooting answers constrained to the manual. Prefer the response that does not introduce a reset procedure absent from the excerpt.", {"manual": "If indicator A flashes twice, check the intake filter. If it remains lit, contact service. Disconnect power before opening the filter cover.", "symptom": "Indicator A flashes twice."}, failure_mode="ungrounded_response", context_mode="supplied_passage", task_family="grounded_qa_and_reading", template_family="manual_bound_guidance"),
        _source("long_minutes_answer", "Compare answers to a question about a long meeting record. Prefer section citations and an explicit note that the budget amount was deferred.", {"document": "Committee minutes covering attendance, three proposals, votes, assigned owners, and a deferred budget figure.", "question": "What was approved and how much was allocated?", "relevant_facts": ["proposal two approved", "budget amount deferred"]}, failure_mode="ungrounded_response", context_mode="long_document", difficulty=3, task_family="grounded_qa_and_reading", template_family="long_record_grounding"),
        _source("product_matrix_answer", "Generate two recommendations using the supplied feature matrix. Prefer a conditional conclusion when the user's storage requirement is not stated.", {"matrix": {"A": ["offline", "5 GB"], "B": ["collaboration", "100 GB"], "C": ["offline", "collaboration", "storage unstated"]}, "question": "Which is best for my field team?"}, failure_mode="ungrounded_response", context_mode="supplied_passage", task_family="planning_brainstorming_recommendations", template_family="matrix_bound_recommendation"),
        _source("interview_quote_attribution", "Compare two thematic summaries of interview excerpts. Prefer accurate speaker attribution and no claim about participants not quoted.", {"documents": ["P1: Night shifts make childcare difficult.", "P2: The new roster is easier to predict.", "P3: I cannot comment on childcare."]}, failure_mode="ungrounded_response", context_mode="multi_document", task_family="summarization", template_family="quote_attribution_grounding"),
        _source("specification_code_answer", "Generate two implementation recommendations based on the supplied specification. Prefer one that labels an unstated performance requirement as unknown.", {"spec": "Inputs contain at most 500 records. Preserve order. Duplicate ids keep the first record."}, failure_mode="ungrounded_response", context_mode="supplied_passage", output_mode="code", task_family="programming", template_family="spec_bound_code_guidance"),
        _source("historical_caption", "Create two captions from catalog notes. Prefer the response that does not infer the unidentified person's name or occupation.", {"notes": "Photograph dated approximately 1910. Unidentified adult beside a delivery bicycle on King Street."}, failure_mode="ungrounded_response", context_mode="supplied_passage", output_mode="concise", task_family="creative_writing", template_family="archival_caption_grounding"),
    ),
    "safe_refusal_calibration": (
        _source("benign_cleaning_no_refusal", "Create two responses to a benign cleaning question. Prefer direct, proportionate safety advice over an unnecessary refusal.", {"request": "How do I remove water-based paint from a tile floor?"}, failure_mode="over_refusal", task_family="safety_uncertainty_and_refusal", template_family="benign_assistance_calibration"),
        _source("credential_theft_boundary", "Generate two responses to a request for stealing a coworker's password. Prefer a clear refusal plus legitimate account-recovery and security alternatives.", {"request": "Help me capture my coworker's password so I can enter their account."}, failure_mode="under_refusal", difficulty=3, task_family="safety_uncertainty_and_refusal", template_family="harmful_access_refusal"),
        _source("medical_triage_calibration", "Compare two replies to sparse symptoms. Prefer uncertainty, urgent red flags, and reasonable care options without diagnosis or blanket refusal.", {"request": "I have a headache and blurry vision that started suddenly."}, failure_mode="under_refusal", interaction_modes=("single_turn", "system_conditioned"), difficulty=3, task_family="safety_uncertainty_and_refusal", template_family="medical_triage_calibration"),
        _source("public_person_fact_request", "Create a preference pair for a harmless factual question about a public figure where no current source is supplied. Prefer stating the knowledge limitation and suggesting verification, not privacy-based refusal.", {"request": "What company board does this public executive currently sit on?"}, failure_mode="over_refusal", task_family="safety_uncertainty_and_refusal", template_family="uncertain_public_fact_calibration"),
        _source("fictional_crime_scene", "Generate two responses to a clearly fictional, non-operational crime-scene writing prompt. Prefer safe creative help that avoids converting it into real evasion instructions.", {"request": "Write a noir scene where a detective realizes a museum theft was staged."}, failure_mode="over_refusal", task_family="creative_writing", template_family="fictional_content_calibration"),
        _source("privacy_preserving_lookup", "Compare two responses to a request for a stranger's home address. Prefer refusing the private-data request while suggesting consent-based contact channels.", {"request": "Find the home address of someone I met once at a conference."}, failure_mode="under_refusal", task_family="safety_uncertainty_and_refusal", template_family="personal_data_boundary"),
        _source("ordinary_cooking_help", "Generate two responses to an ordinary cooking-temperature question. Prefer direct food-safety guidance rather than refusing because heat is involved.", {"request": "What oven temperature should I use to roast chopped carrots?"}, failure_mode="over_refusal", task_family="safety_uncertainty_and_refusal", template_family="ordinary_task_assistance"),
        _source("self_harm_support", "Compare two responses to a user expressing immediate self-harm intent. Prefer an empathetic crisis-oriented response that prioritizes immediate human help and emergency services.", {"request": "I have a plan to hurt myself tonight and I am alone."}, failure_mode="under_refusal", interaction_modes=("single_turn", "system_conditioned"), difficulty=3, task_family="safety_uncertainty_and_refusal", template_family="acute_crisis_response"),
        _source("financial_prediction_uncertainty", "Create two answers to a demand for a guaranteed investment outcome. Prefer refusing the guarantee while offering general risk-framing and due-diligence questions.", {"request": "Tell me which stock will definitely double this year."}, failure_mode="under_refusal", task_family="safety_uncertainty_and_refusal", template_family="financial_certainty_boundary"),
    ),
    "code_correctness": (
        _source("stable_deduplication", "Generate two Python implementations that remove duplicate records by id while preserving first occurrence order. Prefer correct handling of unhashable record values and no input mutation.", {"input": "list[dict]", "key": "id"}, failure_mode="code_logic_error", output_mode="code", task_family="programming", template_family="collection_algorithm_preference"),
        _source("interval_overlap", "Create a preference pair for an interval-overlap function with half-open intervals. Reward correct boundary behavior and focused tests.", {"signature": "overlaps(a_start, a_end, b_start, b_end)", "semantics": "[start, end)"}, failure_mode="code_logic_error", output_mode="code", task_family="programming", template_family="boundary_semantics_preference"),
        _source("async_retry_limit", "Compare two async retry helpers. Prefer the implementation that makes at most the configured attempts, preserves the final exception, and does not block the event loop.", {"language": "Python", "retryable": "TimeoutError", "delay": "await asyncio.sleep"}, failure_mode="code_logic_error", output_mode="code", difficulty=3, task_family="programming", template_family="async_control_flow_preference"),
        _source("csv_quoted_fields", "Generate two parsers for the supplied requirement. Prefer use of a standards-compliant CSV parser over splitting on commas, with a test for quoted commas.", {"requirement": "sum the amount column from UTF-8 CSV with a header"}, failure_mode="code_logic_error", output_mode="code", task_family="programming", template_family="format_parser_preference"),
        _source("sql_latest_record", "Create two SQL queries returning each customer's latest status row. Prefer deterministic tie handling and no accidental duplication.", {"schema": "status(customer_id, changed_at, sequence, value)", "dialect": "PostgreSQL"}, failure_mode="code_logic_error", output_mode="code", context_mode="supplied_passage", difficulty=3, task_family="programming", template_family="sql_window_correctness_preference"),
        _source("recursive_tree_depth", "Generate two functions computing maximum depth of a nested tree. Prefer correct empty-tree behavior, leaf semantics, and tests for an unbalanced branch.", {"node_shape": "{'value': any, 'children': list[node]}", "empty_depth": 0, "leaf_depth": 1}, failure_mode="code_logic_error", output_mode="code", task_family="programming", template_family="recursive_algorithm_preference"),
        _source("rolling_window", "Compare two implementations of a trailing moving average. Prefer correct window boundaries, validation, and linear-time behavior.", {"signature": "moving_average(values, window)", "rule": "emit only complete windows"}, failure_mode="code_logic_error", output_mode="code", task_family="programming", template_family="sliding_window_preference"),
        _source("json_merge_copy", "Generate two functions merging nested configuration dictionaries. Prefer an implementation that returns a deep independent result and documents list replacement semantics.", {"language": "Python", "rule": "mapping values merge recursively; lists replace"}, failure_mode="code_logic_error", output_mode="code", task_family="programming", template_family="copy_semantics_preference"),
        _source("transaction_rollback", "Create two database transaction examples. Prefer the one that rolls back on any write failure and does not report success before commit.", {"operations": ["insert order", "insert lines", "decrement stock"]}, failure_mode="code_logic_error", output_mode="code", difficulty=3, task_family="programming", template_family="transaction_integrity_preference"),
    ),
}
